//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.Services.EmailServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailMessage", Namespace="http://schemas.datacontract.org/2004/07/NTTMNC.BPM.Fx.EmailServices")]
    [System.SerializableAttribute()]
    public partial class EmailMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mcdonalds.AM.Services.EmailServiceReference.WorkflowActionLogForEmail[] ActionLogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> AttachmentsDictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> EmailBodyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ExecutiveSummaryInfoDictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFirstApproveStepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NeedRejectStepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> StoreBasicInfoDictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mcdonalds.AM.Services.EmailServiceReference.WorkflowActionLogForEmail[] ActionLogs {
            get {
                return this.ActionLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionLogsField, value) != true)) {
                    this.ActionLogsField = value;
                    this.RaisePropertyChanged("ActionLogs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AttachmentsDict {
            get {
                return this.AttachmentsDictField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsDictField, value) != true)) {
                    this.AttachmentsDictField = value;
                    this.RaisePropertyChanged("AttachmentsDict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BCC {
            get {
                return this.BCCField;
            }
            set {
                if ((object.ReferenceEquals(this.BCCField, value) != true)) {
                    this.BCCField = value;
                    this.RaisePropertyChanged("BCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CC {
            get {
                return this.CCField;
            }
            set {
                if ((object.ReferenceEquals(this.CCField, value) != true)) {
                    this.CCField = value;
                    this.RaisePropertyChanged("CC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> EmailBodyValues {
            get {
                return this.EmailBodyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailBodyValuesField, value) != true)) {
                    this.EmailBodyValuesField = value;
                    this.RaisePropertyChanged("EmailBodyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExecutiveSummaryInfoDict {
            get {
                return this.ExecutiveSummaryInfoDictField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecutiveSummaryInfoDictField, value) != true)) {
                    this.ExecutiveSummaryInfoDictField = value;
                    this.RaisePropertyChanged("ExecutiveSummaryInfoDict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFirstApproveStep {
            get {
                return this.IsFirstApproveStepField;
            }
            set {
                if ((this.IsFirstApproveStepField.Equals(value) != true)) {
                    this.IsFirstApproveStepField = value;
                    this.RaisePropertyChanged("IsFirstApproveStep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NeedRejectStep {
            get {
                return this.NeedRejectStepField;
            }
            set {
                if ((this.NeedRejectStepField.Equals(value) != true)) {
                    this.NeedRejectStepField = value;
                    this.RaisePropertyChanged("NeedRejectStep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> StoreBasicInfoDict {
            get {
                return this.StoreBasicInfoDictField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreBasicInfoDictField, value) != true)) {
                    this.StoreBasicInfoDictField = value;
                    this.RaisePropertyChanged("StoreBasicInfoDict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateCode {
            get {
                return this.TemplateCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateCodeField, value) != true)) {
                    this.TemplateCodeField = value;
                    this.RaisePropertyChanged("TemplateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowActionLogForEmail", Namespace="http://schemas.datacontract.org/2004/07/NTTMNC.BPM.Fx.EmailServices")]
    [System.SerializableAttribute()]
    public partial class WorkflowActionLogForEmail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mcdonalds.AM.Services.EmailServiceReference.ActionLogType LogTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OperationDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionNameENUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionNameZHCNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionName {
            get {
                return this.ActionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionNameField, value) != true)) {
                    this.ActionNameField = value;
                    this.RaisePropertyChanged("ActionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EID {
            get {
                return this.EIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EIDField, value) != true)) {
                    this.EIDField = value;
                    this.RaisePropertyChanged("EID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mcdonalds.AM.Services.EmailServiceReference.ActionLogType LogType {
            get {
                return this.LogTypeField;
            }
            set {
                if ((this.LogTypeField.Equals(value) != true)) {
                    this.LogTypeField = value;
                    this.RaisePropertyChanged("LogType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OperationDateTime {
            get {
                return this.OperationDateTimeField;
            }
            set {
                if ((this.OperationDateTimeField.Equals(value) != true)) {
                    this.OperationDateTimeField = value;
                    this.RaisePropertyChanged("OperationDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorName {
            get {
                return this.OperatorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorNameField, value) != true)) {
                    this.OperatorNameField = value;
                    this.RaisePropertyChanged("OperatorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionNameENUS {
            get {
                return this.PositionNameENUSField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionNameENUSField, value) != true)) {
                    this.PositionNameENUSField = value;
                    this.RaisePropertyChanged("PositionNameENUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionNameZHCN {
            get {
                return this.PositionNameZHCNField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionNameZHCNField, value) != true)) {
                    this.PositionNameZHCNField = value;
                    this.RaisePropertyChanged("PositionNameZHCN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionLogType", Namespace="http://schemas.datacontract.org/2004/07/NTTMNC.BPM.Fx.EmailServices")]
    public enum ActionLogType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Submit = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approval = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Comments = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailSendingResultType", Namespace="http://schemas.datacontract.org/2004/07/NTTMNC.BPM.Fx.EmailServices")]
    [System.SerializableAttribute()]
    public partial class EmailSendingResultType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InnerErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InnerErrorMessage {
            get {
                return this.InnerErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerErrorMessageField, value) != true)) {
                    this.InnerErrorMessageField = value;
                    this.RaisePropertyChanged("InnerErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailServiceReference.IEmailService")]
    public interface IEmailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendNotificationEmail", ReplyAction="http://tempuri.org/IEmailService/SendNotificationEmailResponse")]
        Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendNotificationEmail(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendNotificationEmail", ReplyAction="http://tempuri.org/IEmailService/SendNotificationEmailResponse")]
        System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendNotificationEmailAsync(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendGBMemoNotificationEmail", ReplyAction="http://tempuri.org/IEmailService/SendGBMemoNotificationEmailResponse")]
        Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendGBMemoNotificationEmail(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendGBMemoNotificationEmail", ReplyAction="http://tempuri.org/IEmailService/SendGBMemoNotificationEmailResponse")]
        System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendGBMemoNotificationEmailAsync(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendRecallEmail", ReplyAction="http://tempuri.org/IEmailService/SendRecallEmailResponse")]
        Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendRecallEmail(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendRecallEmail", ReplyAction="http://tempuri.org/IEmailService/SendRecallEmailResponse")]
        System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendRecallEmailAsync(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendCommentsEmail", ReplyAction="http://tempuri.org/IEmailService/SendCommentsEmailResponse")]
        Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendCommentsEmail(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendCommentsEmail", ReplyAction="http://tempuri.org/IEmailService/SendCommentsEmailResponse")]
        System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendCommentsEmailAsync(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendApprovalEmail", ReplyAction="http://tempuri.org/IEmailService/SendApprovalEmailResponse")]
        Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendApprovalEmail(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendApprovalEmail", ReplyAction="http://tempuri.org/IEmailService/SendApprovalEmailResponse")]
        System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendApprovalEmailAsync(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendApprovalWithRejectEmail", ReplyAction="http://tempuri.org/IEmailService/SendApprovalWithRejectEmailResponse")]
        Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendApprovalWithRejectEmail(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendApprovalWithRejectEmail", ReplyAction="http://tempuri.org/IEmailService/SendApprovalWithRejectEmailResponse")]
        System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendApprovalWithRejectEmailAsync(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendEmail", ReplyAction="http://tempuri.org/IEmailService/SendEmailResponse")]
        Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendEmail(string to, string subject, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendEmail", ReplyAction="http://tempuri.org/IEmailService/SendEmailResponse")]
        System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendEmailAsync(string to, string subject, string content);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailServiceChannel : Mcdonalds.AM.Services.EmailServiceReference.IEmailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailServiceClient : System.ServiceModel.ClientBase<Mcdonalds.AM.Services.EmailServiceReference.IEmailService>, Mcdonalds.AM.Services.EmailServiceReference.IEmailService {
        
        public EmailServiceClient() {
        }
        
        public EmailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendNotificationEmail(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage) {
            return base.Channel.SendNotificationEmail(emailMessage);
        }
        
        public System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendNotificationEmailAsync(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage) {
            return base.Channel.SendNotificationEmailAsync(emailMessage);
        }
        
        public Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendGBMemoNotificationEmail(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage) {
            return base.Channel.SendGBMemoNotificationEmail(emailMessage);
        }
        
        public System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendGBMemoNotificationEmailAsync(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage) {
            return base.Channel.SendGBMemoNotificationEmailAsync(emailMessage);
        }
        
        public Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendRecallEmail(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage) {
            return base.Channel.SendRecallEmail(emailMessage);
        }
        
        public System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendRecallEmailAsync(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage) {
            return base.Channel.SendRecallEmailAsync(emailMessage);
        }
        
        public Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendCommentsEmail(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage) {
            return base.Channel.SendCommentsEmail(emailMessage);
        }
        
        public System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendCommentsEmailAsync(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage) {
            return base.Channel.SendCommentsEmailAsync(emailMessage);
        }
        
        public Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendApprovalEmail(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage) {
            return base.Channel.SendApprovalEmail(emailMessage);
        }
        
        public System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendApprovalEmailAsync(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage) {
            return base.Channel.SendApprovalEmailAsync(emailMessage);
        }
        
        public Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendApprovalWithRejectEmail(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage) {
            return base.Channel.SendApprovalWithRejectEmail(emailMessage);
        }
        
        public System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendApprovalWithRejectEmailAsync(Mcdonalds.AM.Services.EmailServiceReference.EmailMessage emailMessage) {
            return base.Channel.SendApprovalWithRejectEmailAsync(emailMessage);
        }
        
        public Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType SendEmail(string to, string subject, string content) {
            return base.Channel.SendEmail(to, subject, content);
        }
        
        public System.Threading.Tasks.Task<Mcdonalds.AM.Services.EmailServiceReference.EmailSendingResultType> SendEmailAsync(string to, string subject, string content) {
            return base.Channel.SendEmailAsync(to, subject, content);
        }
    }
}
