//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentsMemoProcessInfo
    {
        public System.Guid Id { get; set; }
        public string MemoCode { get; set; }
        public string FlowCode { get; set; }
        public string ProjectId { get; set; }
        public string USCode { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<System.DateTime> NotifyDate { get; set; }
        public bool IsNotified { get; set; }
        public string CreateUserAccount { get; set; }
    }
}
