//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosureMemo
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public string RegionCode { get; set; }
        public string RegionNameZHCN { get; set; }
        public string RegionNameENUS { get; set; }
        public string MarketCode { get; set; }
        public string MarketNameZHCN { get; set; }
        public string MarketNameENUS { get; set; }
        public string ProvinceCode { get; set; }
        public string ProvinceNameZHCN { get; set; }
        public string ProvinceNameENUS { get; set; }
        public string CityCode { get; set; }
        public string CityNameENUS { get; set; }
        public string CityNameZHCN { get; set; }
        public string USCode { get; set; }
        public string StoreNameENUS { get; set; }
        public string StoreNameZHCN { get; set; }
        public string StoreAddressENUS { get; set; }
        public string StoreAddressZHCN { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public ClosureNatureType ClosureNature { get; set; }
        public Nullable<bool> PermanentCloseOpportunity { get; set; }
        public Nullable<bool> HasRelocationPlan { get; set; }
        public Nullable<int> PipelineId { get; set; }
        public string PipelineName { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> BecauseOfReimaging { get; set; }
        public Nullable<bool> BecauseOfRemodel { get; set; }
        public Nullable<bool> BecauseOfDespute { get; set; }
        public Nullable<bool> BecauseOfRedevelopment { get; set; }
        public Nullable<bool> BecauseOfPlanedClosure { get; set; }
        public Nullable<bool> BecauseOfRebuild { get; set; }
        public string BecauseOfOthers { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<bool> CompensationAwarded { get; set; }
        public Nullable<decimal> Compensation { get; set; }
    }
}
