//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosureContractRefund
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public Nullable<System.DateTime> RefundTime { get; set; }
        public Nullable<bool> IsRental { get; set; }
        public string IsRentalDesc { get; set; }
        public Nullable<bool> IsRedLine { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreaetUserAccount { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsLeaseTerm { get; set; }
        public string IsRedLineDesc { get; set; }
        public string IsLeaseTermDesc { get; set; }
    }
}
