//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosureWOCheckList
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public Nullable<int> ProcInstID { get; set; }
        public string Foilo { get; set; }
        public Nullable<decimal> RE_Original { get; set; }
        public Nullable<decimal> LHI_Original { get; set; }
        public Nullable<decimal> ESSD_Original { get; set; }
        public Nullable<decimal> Equipment_Original { get; set; }
        public Nullable<decimal> Signage_Original { get; set; }
        public Nullable<decimal> Seating_Original { get; set; }
        public Nullable<decimal> Decoration_Original { get; set; }
        public Nullable<decimal> TotalCost_Original { get; set; }
        public Nullable<decimal> RE_NBV { get; set; }
        public Nullable<decimal> LHI_NBV { get; set; }
        public Nullable<decimal> ESSD_NBV { get; set; }
        public Nullable<decimal> Equipment_NBV { get; set; }
        public Nullable<decimal> Signage_NBV { get; set; }
        public Nullable<decimal> Seating_NBV { get; set; }
        public Nullable<decimal> Decoration_NBV { get; set; }
        public Nullable<decimal> TotalCost_NBV { get; set; }
        public Nullable<decimal> ClosingCost { get; set; }
        public Nullable<decimal> EquipmentTransfer { get; set; }
        public Nullable<decimal> TotalWriteOFF { get; set; }
        public Nullable<decimal> RECost_WriteOFF { get; set; }
        public Nullable<decimal> LHI_WriteOFF { get; set; }
        public Nullable<decimal> ESSD_WriteOFF { get; set; }
        public Nullable<decimal> Equipment_WriteOFF { get; set; }
        public Nullable<decimal> Signage_WriteOFF { get; set; }
        public Nullable<decimal> Seating_WriteOFF { get; set; }
        public Nullable<decimal> Decoration_WriteOFF { get; set; }
        public Nullable<decimal> TotalCost_WriteOFF { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string LastUpdateUserAccount { get; set; }
        public string LastUpdateUserNameZHCN { get; set; }
        public string LastUpdateUserNameENUS { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<double> ProgressRate { get; set; }
        public Nullable<bool> IsHistory { get; set; }
        public string Compensation { get; set; }
        public string PMSupervisorAccount { get; set; }
        public string PMSupervisorName { get; set; }
        public string MCCLApproverAccount { get; set; }
        public string MCCLApproverName { get; set; }
        public string MCCLITApproverAccount { get; set; }
        public string MCCLITApproverName { get; set; }
        public string MCCLMCCLEqApproverAccount { get; set; }
        public string MCCLMCCLEqApproverName { get; set; }
        public Nullable<bool> RefreshClosureTool { get; set; }
    }
}
