//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosureContractInfo
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public string FirstParty { get; set; }
        public string MCDOwersShop { get; set; }
        public string OwnerContact { get; set; }
        public string ContractModeName { get; set; }
        public string RentType { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> EstimateStartTime { get; set; }
        public Nullable<System.DateTime> EstimateEndTime { get; set; }
        public Nullable<int> ContractStartYear { get; set; }
        public Nullable<int> ContractEndYear { get; set; }
        public Nullable<System.DateTime> LastSubmitTime { get; set; }
        public Nullable<bool> Is2010YearModefied { get; set; }
        public string RentStructure { get; set; }
        public Nullable<bool> IsEarlierDate { get; set; }
        public string EarlierDateDesc { get; set; }
        public string RentPayer { get; set; }
        public string RentPayWay { get; set; }
        public Nullable<System.DateTime> RentPayDate { get; set; }
        public Nullable<bool> IsDepositeMoney { get; set; }
        public Nullable<decimal> DepositeMoney { get; set; }
        public Nullable<bool> IsDepositeRefund { get; set; }
        public Nullable<System.DateTime> DepositeRefundDate { get; set; }
        public string IsOverduePayClause { get; set; }
        public Nullable<bool> IsBankGuarantee { get; set; }
        public string BankGuaranteeCode { get; set; }
        public Nullable<decimal> BankGuaranteeMoney { get; set; }
        public Nullable<System.DateTime> BankGuaranteeStartTime { get; set; }
        public Nullable<System.DateTime> BankGuaranteeEndTime { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<int> PurchaseAuthorityYear { get; set; }
        public Nullable<int> MaturityYear { get; set; }
        public string USCode { get; set; }
    }
}
