//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosureTool
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public Nullable<int> ProcInstID { get; set; }
        public Nullable<decimal> TotalSales_Adjustment_RMB { get; set; }
        public Nullable<decimal> CompSales_Adjustment { get; set; }
        public Nullable<decimal> CompSalesMacket_Adjustment { get; set; }
        public Nullable<decimal> CompCG_Adjustment { get; set; }
        public Nullable<decimal> CompCGMacket_Adjustment { get; set; }
        public Nullable<decimal> PAC_RMB_Adjustment { get; set; }
        public Nullable<decimal> PAC_Adjustment { get; set; }
        public Nullable<decimal> PACMarket_Adjustment { get; set; }
        public Nullable<decimal> Rent_RMB_Adjustment { get; set; }
        public Nullable<decimal> DepreciationLHI_RMB_Adjustment { get; set; }
        public Nullable<decimal> InterestLHI_RMB_Adjustment { get; set; }
        public Nullable<decimal> ServiceFee_RMB_Adjustment { get; set; }
        public Nullable<decimal> Accounting_RMB_Adjustment { get; set; }
        public Nullable<decimal> Insurance_RMB_Adjustment { get; set; }
        public Nullable<decimal> TaxesLicenses_RMB_Adjustment { get; set; }
        public Nullable<decimal> Depreciation_ESSD_RMB_Adjustment { get; set; }
        public Nullable<decimal> Interest_ESSD_RMB_Adjustment { get; set; }
        public Nullable<decimal> OtherIncExp_RMB_Adjustment { get; set; }
        public Nullable<decimal> Product_Sales_RMB_Adjustment { get; set; }
        public Nullable<decimal> NonProduct_Sales_RMB_Adjustment { get; set; }
        public Nullable<decimal> NonProduct_Costs_RMB_Adjustment { get; set; }
        public Nullable<decimal> TotalSales_RMB { get; set; }
        public Nullable<decimal> CompSales { get; set; }
        public Nullable<decimal> CompSalesMacket { get; set; }
        public Nullable<decimal> CompCG { get; set; }
        public Nullable<decimal> CompCGMacket { get; set; }
        public Nullable<decimal> PAC_RMB { get; set; }
        public Nullable<decimal> PAC { get; set; }
        public Nullable<decimal> PACMarket { get; set; }
        public Nullable<decimal> Rent_RMB { get; set; }
        public Nullable<decimal> DepreciationLHI_RMB { get; set; }
        public Nullable<decimal> InterestLHI_RMB { get; set; }
        public Nullable<decimal> ServiceFee_RMB { get; set; }
        public Nullable<decimal> Accounting_RMB { get; set; }
        public Nullable<decimal> Insurance_RMB { get; set; }
        public Nullable<decimal> TaxesLicenses_RMB { get; set; }
        public Nullable<decimal> Depreciation_ESSD_RMB { get; set; }
        public Nullable<decimal> Interest_ESSD_RMB { get; set; }
        public Nullable<decimal> OtherIncExp_RMB { get; set; }
        public Nullable<decimal> Product_Sales_RMB { get; set; }
        public Nullable<decimal> NonProduct_Sales_RMB { get; set; }
        public Nullable<decimal> NonProduct_Costs_RMB { get; set; }
        public Nullable<decimal> SOI_Adjustment { get; set; }
        public Nullable<decimal> SOIMarket_Adjustment { get; set; }
        public Nullable<decimal> CashFlow_RMB_Adjustment { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserAccount { get; set; }
        public Nullable<decimal> CompSales_TTMY1 { get; set; }
        public Nullable<decimal> CompSales_TTMY2 { get; set; }
        public Nullable<decimal> CompSales_Market_TTMY1 { get; set; }
        public Nullable<decimal> CompSales_Market_TTMY2 { get; set; }
        public Nullable<decimal> CompGC_TTMY1 { get; set; }
        public Nullable<decimal> CompGC_TTMY2 { get; set; }
        public Nullable<decimal> CompGCMarket_TTMY1 { get; set; }
        public Nullable<decimal> CompGCMarket_TTMY2 { get; set; }
        public Nullable<decimal> PAC_TTMY1 { get; set; }
        public Nullable<decimal> PAC_TTMY2 { get; set; }
        public Nullable<decimal> PACMarket_TTMY1 { get; set; }
        public Nullable<decimal> PACMarket_TTMY2 { get; set; }
        public Nullable<decimal> SOI_TTMY1 { get; set; }
        public Nullable<decimal> SOI_TTMY2 { get; set; }
        public Nullable<decimal> SOIMarket_TTMY1 { get; set; }
        public Nullable<decimal> SOIMarket_TTMY2 { get; set; }
        public Nullable<decimal> CashFlow_TTMY1 { get; set; }
        public Nullable<decimal> CashFlow_TTMY2 { get; set; }
        public Nullable<decimal> Status { get; set; }
        public Nullable<decimal> TotalSales_TTMY1 { get; set; }
        public Nullable<decimal> TotalSales_TTMY2 { get; set; }
        public Nullable<decimal> MccpcoCashFlow { get; set; }
        public Nullable<decimal> McppcoMargin { get; set; }
        public Nullable<bool> IsOptionOffered { get; set; }
        public string LeaseTerm { get; set; }
        public Nullable<decimal> Investment { get; set; }
        public Nullable<decimal> NPVRestaurantCashflows { get; set; }
        public Nullable<decimal> Yr1SOI { get; set; }
        public Nullable<decimal> IRR { get; set; }
        public Nullable<decimal> CompAssumption { get; set; }
        public Nullable<decimal> CashflowGrowth { get; set; }
        public Nullable<decimal> SOI { get; set; }
        public Nullable<decimal> SOIMarket { get; set; }
        public Nullable<decimal> Compensation { get; set; }
        public Nullable<bool> IsHistory { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string LastUpdateUserAccount { get; set; }
        public string LastUpdateUserNameZHCN { get; set; }
        public string LastUpdateUserNameENUS { get; set; }
        public string ConclusionComment { get; set; }
        public Nullable<decimal> TotalOneOffCosts { get; set; }
        public Nullable<decimal> OperatingIncome { get; set; }
        public Nullable<decimal> CompensationReceipt { get; set; }
        public Nullable<decimal> ClosingCosts { get; set; }
        public Nullable<double> NPVSC { get; set; }
        public Nullable<int> RelocationPipelineID { get; set; }
        public string PipelineName { get; set; }
    }
}
