//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSync_LDW_AM_BEInfo
    {
        public int BEID { get; set; }
        public string BECode { get; set; }
        public string BETypeName { get; set; }
        public int StoreID { get; set; }
        public int ParentStoreID { get; set; }
        public string BEType { get; set; }
        public string LaunchDate { get; set; }
        public string CloseDate { get; set; }
    }
}
