//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSync_LDW_AM_STBEMonthSales
    {
        public int ItemID { get; set; }
        public string StoreCode { get; set; }
        public string BeCode { get; set; }
        public string FinanceYear { get; set; }
        public string FinanceMonth { get; set; }
        public string BEType { get; set; }
        public string Remark { get; set; }
        public string LaunchDate { get; set; }
        public string CloseDate { get; set; }
        public string MonthlyNetTotalSales { get; set; }
        public string MonthlyTotalGC { get; set; }
    }
}
