//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSync_AM_PMT_StoreContractInfo
    {
        public System.Guid Id { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string StoreCode { get; set; }
        public Nullable<int> LeaseRecapID { get; set; }
        public string PartyAFullName { get; set; }
        public string McDLegalEntity { get; set; }
        public string McDOwnership { get; set; }
        public string ContactPerson { get; set; }
        public string ContactMode { get; set; }
        public string RentType { get; set; }
        public string TotalLeasedArea { get; set; }
        public string LeasePurchaseTerm { get; set; }
        public string LeasePurchase { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string StartYear { get; set; }
        public Nullable<System.DateTime> RentCommencementDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EndYear { get; set; }
        public string DeadlineToNotice { get; set; }
        public Nullable<int> Changedafter2010 { get; set; }
        public string RentStructure { get; set; }
        public Nullable<int> WithEarlyTerminationClause { get; set; }
        public string EarlyTerminationClauseDetail { get; set; }
        public string RentalPaidto { get; set; }
        public string RentPaymentArrangement { get; set; }
        public Nullable<int> HasDeposit { get; set; }
        public string DepositAmount { get; set; }
        public Nullable<int> Refundable { get; set; }
        public string RefundableDate { get; set; }
        public Nullable<int> WithPenaltyClause { get; set; }
        public Nullable<int> HasBankGuarantee { get; set; }
        public string BGNumber { get; set; }
        public string BGAmount { get; set; }
        public string BGCommencementDate { get; set; }
        public string BGEndDate { get; set; }
        public string FilePath { get; set; }
        public string OverallAccessibility { get; set; }
        public string RentSupervalueDay { get; set; }
        public string Keyword3 { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<System.DateTime> SyncTime { get; set; }
    }
}
