//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSync_PMT_AM_StoreDevelop
    {
        public System.Guid Id { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string StoreCode { get; set; }
        public string AssetRepID { get; set; }
        public string AssetRepAD { get; set; }
        public string AssetRepEid { get; set; }
        public string AssetRepName { get; set; }
        public string AssetMgrID { get; set; }
        public string AssetMgrAD { get; set; }
        public string AssetMgrEid { get; set; }
        public string AssetMgrName { get; set; }
        public string PlannerID { get; set; }
        public string PlannerAD { get; set; }
        public string PlannerEid { get; set; }
        public string PlannerName { get; set; }
        public string ProjectManagerID { get; set; }
        public string ProjectManagerAD { get; set; }
        public string ProjectManagerEid { get; set; }
        public string ProjectManagerName { get; set; }
        public string PlannerMgrID { get; set; }
        public string PlannerMgrAD { get; set; }
        public string PlannerMgrEid { get; set; }
        public string PlannerMgrName { get; set; }
        public string ConsMgrID { get; set; }
        public string ConsMgrAD { get; set; }
        public string ConsMgrEid { get; set; }
        public string ConsMgrName { get; set; }
        public string RERepID { get; set; }
        public string RERepAD { get; set; }
        public string RERepEid { get; set; }
        public string RERepName { get; set; }
        public string REMgrID { get; set; }
        public string REMgrAD { get; set; }
        public string REMgrEid { get; set; }
        public string REMgrName { get; set; }
        public Nullable<System.DateTime> SyncTime { get; set; }
    }
}
