//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSync_AM_PMT_StoreSTMonthlyFinaceInfo
    {
        public System.Guid Id { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string StoreCode { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string NetProductSales { get; set; }
        public string CashFlow { get; set; }
        public string SOI { get; set; }
        public string Rent { get; set; }
        public string McOpCoMargin { get; set; }
        public string Rent_inclAdjustment { get; set; }
        public string Rent_inclAdjustmentPct { get; set; }
        public string LHINBV { get; set; }
        public string ESSDNBV { get; set; }
        public string TotalNBV { get; set; }
        public string CompsSales { get; set; }
        public string CompSalePreYr1 { get; set; }
        public string CompSalePreYr2 { get; set; }
        public string CompSalePreYr3 { get; set; }
        public string SOIPreYr1 { get; set; }
        public string SOIPreYr2 { get; set; }
        public string SOIPreYr3 { get; set; }
        public string SOIPctPreYr1 { get; set; }
        public string SOIPctPreYr2 { get; set; }
        public string SOIPctPreYr3 { get; set; }
        public string TotalNetSalesPreYr1 { get; set; }
        public string TotalNetSalesPreYr2 { get; set; }
        public string TotalNetSalesPreYr3 { get; set; }
        public string CashFlowPreYr1 { get; set; }
        public string CashFlowPreYr2 { get; set; }
        public string CashFlowPreYr3 { get; set; }
        public string RentalPaidtoLLPreYr1 { get; set; }
        public string RentalPaidtoLLPreYr2 { get; set; }
        public string RentalPaidtoLLPreYr3 { get; set; }
        public string SOIPct { get; set; }
        public Nullable<System.DateTime> SyncTime { get; set; }
    }
}
