//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public ActionType Action { get; set; }
        public string Operator { get; set; }
        public string OperatorTitle { get; set; }
        public string OperatorZHCN { get; set; }
        public string OperatorENUS { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
