//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproveDialogUser
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public string RefTableID { get; set; }
        public string FlowCode { get; set; }
        public string MarketMgrCode { get; set; }
        public string RegionalMgrCode { get; set; }
        public string DDCode { get; set; }
        public string MDDCode { get; set; }
        public string GMCode { get; set; }
        public string FCCode { get; set; }
        public string RDDCode { get; set; }
        public string VPGMCode { get; set; }
        public string CDOCode { get; set; }
        public string CFOCode { get; set; }
        public string ConstructionManagerCode { get; set; }
        public string MCCLConsManagerCode { get; set; }
        public string FMCode { get; set; }
        public string FinanceControllerCode { get; set; }
        public string MngDirectorCode { get; set; }
        public string LegalCode { get; set; }
        public string MCCLAssetMgrCode { get; set; }
        public string MCCLAssetDtrCode { get; set; }
        public string NoticeUsers { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string LastUpdateUserAccount { get; set; }
        public string GeneralCounselCode { get; set; }
        public string NecessaryNoticeUsers { get; set; }
    }
}
