//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentRequirement
    {
        public System.Guid Id { get; set; }
        public string NameZHCN { get; set; }
        public string NameENUS { get; set; }
        public string RefTableName { get; set; }
        public string Extension { get; set; }
        public int Sequence { get; set; }
        public Nullable<System.Guid> LinkTo { get; set; }
        public bool Required { get; set; }
        public string FlowCode { get; set; }
        public string NodeCode { get; set; }
        public string TypeCode { get; set; }
    }
}
