//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosureToolImpactOtherStore
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ClosureId { get; set; }
        public string StoreCode { get; set; }
        public string NameZHCN { get; set; }
        public string NameENUS { get; set; }
        public Nullable<decimal> ImpactSaltes { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserAccount { get; set; }
    }
}
