//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosureConsInvtChecking
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public Nullable<int> ProcInstID { get; set; }
        public Nullable<decimal> TotalOriginalBudget { get; set; }
        public Nullable<decimal> TotalNBVBudget { get; set; }
        public Nullable<decimal> TotalWriteoffBudget { get; set; }
        public Nullable<decimal> RECostBudget { get; set; }
        public Nullable<decimal> LHIBudget { get; set; }
        public Nullable<decimal> EquipmentBudget { get; set; }
        public Nullable<decimal> SignageBudget { get; set; }
        public Nullable<decimal> SeatingBudget { get; set; }
        public Nullable<decimal> DecorationBudget { get; set; }
        public Nullable<decimal> ClosingCostBudegt { get; set; }
        public Nullable<decimal> ClosingCostActual { get; set; }
        public Nullable<decimal> TotalActual { get; set; }
        public Nullable<decimal> RECostActual { get; set; }
        public Nullable<decimal> LHIActual { get; set; }
        public Nullable<decimal> EquipmentActual { get; set; }
        public Nullable<decimal> SignageActual { get; set; }
        public Nullable<decimal> SeatingActual { get; set; }
        public Nullable<decimal> DecorationActual { get; set; }
        public Nullable<decimal> RECostVsBudget { get; set; }
        public Nullable<decimal> LHIWOVsBudget { get; set; }
        public Nullable<decimal> ESSDWOVsBudget { get; set; }
        public Nullable<decimal> TTLWOVsBudget { get; set; }
        public string REExplanation { get; set; }
        public string LHIExplanation { get; set; }
        public string ESSDExplanation { get; set; }
        public string TotalExplanation { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserAccount { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<bool> IsHistory { get; set; }
        public Nullable<decimal> ESSDBudget { get; set; }
    }
}
