//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSync_PMT_AM_StoreOps
    {
        public System.Guid Id { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string StoreCode { get; set; }
        public string VPGMID { get; set; }
        public string VPGMAD { get; set; }
        public string VPGMEid { get; set; }
        public string VPGMName { get; set; }
        public string GMID { get; set; }
        public string GMAD { get; set; }
        public string GMEid { get; set; }
        public string GMName { get; set; }
        public string DOID { get; set; }
        public string DOAD { get; set; }
        public string DOEid { get; set; }
        public string DOName { get; set; }
        public string OMID { get; set; }
        public string OMAD { get; set; }
        public string OMEid { get; set; }
        public string OMName { get; set; }
        public string OCID { get; set; }
        public string OCAD { get; set; }
        public string OCEid { get; set; }
        public string OCName { get; set; }
        public string StoreManagerID { get; set; }
        public string StoreManagerAD { get; set; }
        public string StoreManagerEid { get; set; }
        public string StoreManagerName { get; set; }
        public string StorePhone { get; set; }
        public string StoreEmail { get; set; }
        public Nullable<System.DateTime> SyncTime { get; set; }
    }
}
