//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSync_AM_PMT_StoreSTLLRecord
    {
        public System.Guid Id { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string StoreCode { get; set; }
        public string LL0Contact { get; set; }
        public string LL0Title { get; set; }
        public string LL0Tel { get; set; }
        public string LL0Address { get; set; }
        public string LL1Contact { get; set; }
        public string LL1Title { get; set; }
        public string LL1Tel { get; set; }
        public string LL1Mobile { get; set; }
        public string LL2Contact { get; set; }
        public string LL2Title { get; set; }
        public string LL2Tel { get; set; }
        public string LL2Mobile { get; set; }
        public string LL3Contact { get; set; }
        public string LL3Title { get; set; }
        public string LL3Tel { get; set; }
        public string LL3Mobile { get; set; }
        public Nullable<int> IsBroker { get; set; }
        public string BrokerName { get; set; }
        public Nullable<int> IsAlliance { get; set; }
        public string AllianceName { get; set; }
        public string SignageCount { get; set; }
        public Nullable<int> IsBigLL { get; set; }
        public string BigLLName { get; set; }
        public string OpenCount { get; set; }
        public Nullable<int> IsFromRE { get; set; }
        public string DateTime { get; set; }
        public string Location { get; set; }
        public string Topic { get; set; }
        public string McdParticipants { get; set; }
        public string McdParticipantsAD { get; set; }
        public string LLparticipants { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> SyncTime { get; set; }
    }
}
