//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSync_PMT_AM_StoreAssetHandover
    {
        public System.Guid Id { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string StoreCode { get; set; }
        public string LL1Contact1 { get; set; }
        public string LL1Title1 { get; set; }
        public string LL1Tel1 { get; set; }
        public string LL1Mobile1 { get; set; }
        public string LL1Contact2 { get; set; }
        public string LL1Title2 { get; set; }
        public string LL1Tel2 { get; set; }
        public string LL1Mobile2 { get; set; }
        public string LL1ZipCode { get; set; }
        public string LL1Address { get; set; }
        public string LL2Contact1 { get; set; }
        public string LL2Title1 { get; set; }
        public string LL2Tel1 { get; set; }
        public string LL2Mobile1 { get; set; }
        public string LL2Contact2 { get; set; }
        public string LL2Title2 { get; set; }
        public string LL2Tel2 { get; set; }
        public string LL2Mobile2 { get; set; }
        public string LL2ZipCode { get; set; }
        public string LL2Address { get; set; }
        public string OwnerContact1 { get; set; }
        public string OwnerTitle1 { get; set; }
        public string OwnerTel1 { get; set; }
        public string OwnerMobile1 { get; set; }
        public string OwnerContact2 { get; set; }
        public string OwnerTitle2 { get; set; }
        public string OwnerTel2 { get; set; }
        public string OwnerMobile2 { get; set; }
        public string OwnerZipCode { get; set; }
        public string OwnerAddress { get; set; }
        public string PropertyContact1 { get; set; }
        public string PropertyTitle1 { get; set; }
        public string PropertyTel1 { get; set; }
        public string PropertyMobile1 { get; set; }
        public string PropertyContact2 { get; set; }
        public string PropertyTitle2 { get; set; }
        public string PropertyTel2 { get; set; }
        public string PropertyMobile2 { get; set; }
        public string PropertyZipCode { get; set; }
        public string PropertyAddress { get; set; }
        public Nullable<int> Property1YesNo { get; set; }
        public Nullable<System.DateTime> Property1PlanTime { get; set; }
        public Nullable<System.DateTime> Property1FinalTime { get; set; }
        public Nullable<int> Property2YesNo { get; set; }
        public string Property2Remark { get; set; }
        public Nullable<int> Property3YesNo { get; set; }
        public string Property3Remark { get; set; }
        public Nullable<int> Property4YesNo { get; set; }
        public string Property4Remark { get; set; }
        public Nullable<int> Property5YesNo { get; set; }
        public string Property5Remark { get; set; }
        public Nullable<int> Property6YesNo { get; set; }
        public string Property6Remark { get; set; }
        public Nullable<int> Property7YesNo { get; set; }
        public string Property7Remark { get; set; }
        public Nullable<int> Property8YesNo { get; set; }
        public string Property8Remark { get; set; }
        public Nullable<int> Property9YesNo { get; set; }
        public string Property9Remark { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> SyncTime { get; set; }
    }
}
