//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSync_AM_PMT_StoreBEContractInfo
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> StoreBEInfoIdentifier { get; set; }
        public Nullable<int> BEID { get; set; }
        public string BeName { get; set; }
        public string LandlordName { get; set; }
        public string Rental { get; set; }
        public string McDLegalEntity { get; set; }
        public string ContactPerson { get; set; }
        public string Size { get; set; }
        public string LeaseTerm { get; set; }
        public string LeaseStartDate { get; set; }
        public string LeaseEndDate { get; set; }
        public string ContactMode { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> SyncTime { get; set; }
    }
}
