//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSync_PMT_AM_Position
    {
        public int ID { get; set; }
        public int PositionID { get; set; }
        public Nullable<int> JoinID { get; set; }
        public string CnName { get; set; }
        public string EnName { get; set; }
        public string Comments { get; set; }
        public string MnemonicCode { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserID { get; set; }
        public string DepartmentCode { get; set; }
        public string Target { get; set; }
        public int ShowInTrack { get; set; }
        public string StoreType { get; set; }
        public Nullable<int> Alliance { get; set; }
        public Nullable<int> Broker { get; set; }
        public string SectionCode { get; set; }
        public string nameCode { get; set; }
        public Nullable<System.DateTime> SyncTime { get; set; }
    }
}
