//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSync_AM_PMT_StoreMMInfo
    {
        public System.Guid Id { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string StoreCode { get; set; }
        public string MMName { get; set; }
        public string MMCode { get; set; }
        public string Priority { get; set; }
        public string Population { get; set; }
        public string TACode { get; set; }
        public string TAName { get; set; }
        public string TAType { get; set; }
        public string TAAPriority { get; set; }
        public string Desirability { get; set; }
        public string Maturity { get; set; }
        public string TASize { get; set; }
        public string IncomeLevel { get; set; }
        public string StoreTypeName { get; set; }
        public string PortfolioTypeName { get; set; }
        public string LocationRatingPP { get; set; }
        public Nullable<int> BackDistance { get; set; }
        public string OverallVisibility { get; set; }
        public string OverallAccessibility { get; set; }
        public string Keyword1 { get; set; }
        public string Keyword2 { get; set; }
        public string Keyword3 { get; set; }
        public string IsNearStreet { get; set; }
        public string StrategicInvestmentType { get; set; }
        public string NatZone { get; set; }
        public Nullable<int> IsAlliance { get; set; }
        public string AllianceName { get; set; }
        public Nullable<int> IsBigLL { get; set; }
        public string BigLLName { get; set; }
        public string NearestStorePP { get; set; }
        public string NearestDistancePP { get; set; }
        public string NearestMcDOpenDate { get; set; }
        public string NearestMcDAUV { get; set; }
        public string EstimatedImpactOnPp { get; set; }
        public string SecondNearestStorePP { get; set; }
        public string SecondNearestDistancePP { get; set; }
        public string Nearest2ndMcDOpenDate { get; set; }
        public string Nearest2ndMcDAUV { get; set; }
        public string EstimatedImpactOnPp2 { get; set; }
        public string NearestKFC { get; set; }
        public string NearestKFCDist { get; set; }
        public string KFCOpenDate { get; set; }
        public string NearestKFCY1Sales { get; set; }
        public string HomePop { get; set; }
        public string HomeIncomeLevel { get; set; }
        public string HomeSalesPct { get; set; }
        public string WorkersNo { get; set; }
        public string WorkersProfile { get; set; }
        public string WorkSalesPct { get; set; }
        public string SchoolStudentNo { get; set; }
        public string SchoolStudentProfile { get; set; }
        public string SchoolSalesPct { get; set; }
        public string ShoppingLevel { get; set; }
        public string ShopMallsNo { get; set; }
        public string ShopTotalCommercialSize { get; set; }
        public string ShopSteetLength { get; set; }
        public string BuildingNature { get; set; }
        public string BuildingOpenDate { get; set; }
        public string BuildingRetailActStrength { get; set; }
        public string BuildingAnchor1Name { get; set; }
        public string BuildingAnchor1Size { get; set; }
        public string BuildingAnchor2Name { get; set; }
        public string BuildingAnchor2Size { get; set; }
        public string ShopSalesPct { get; set; }
        public string THType { get; set; }
        public string THStoreLocation { get; set; }
        public string StoreLocatedon { get; set; }
        public string THTurnoverCount { get; set; }
        public string THMainCmpLocatedon { get; set; }
        public string THSalesPct { get; set; }
        public string LeisureNature { get; set; }
        public string LeisureSalesPct { get; set; }
        public string OtherFactorsName { get; set; }
        public string OtherSalesPct { get; set; }
        public string HomeRemark { get; set; }
        public string WorkRemark { get; set; }
        public string ShopRemark { get; set; }
        public string SchoolRemark { get; set; }
        public string THRemark { get; set; }
        public string LeisureRemark { get; set; }
        public string OthersRemark { get; set; }
        public string SubwayLines { get; set; }
        public string SubwayClosetExitDist { get; set; }
        public string SubwayVisibility { get; set; }
        public string BusStopNo { get; set; }
        public string BusLines { get; set; }
        public string BusClosetStopDist { get; set; }
        public string CompetitorsNo { get; set; }
        public string CompetitorsTop3Name { get; set; }
        public string KFCCount { get; set; }
        public string KFCY1Count { get; set; }
        public string KFCAvgSales { get; set; }
        public string NearestKFCY1Sales2 { get; set; }
        public string BuildingCommercialSize { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> SyncTime { get; set; }
    }
}
