//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSync_LDW_AM_STFinanceData2
    {
        public int FinanceDataID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string FinanceYear { get; set; }
        public string FinanceMonth { get; set; }
        public string UsCode { get; set; }
        public string HomeSales_Pct { get; set; }
        public string WorkSales_Pct { get; set; }
        public string SchoolSales_Pct { get; set; }
        public string ShopSales_Pct { get; set; }
        public string TransportationHubSales_Pct { get; set; }
        public string LeisureSales_Pct { get; set; }
        public string OtherSales_Pct { get; set; }
        public string LHICIC_OriginalInvestment { get; set; }
        public string ESSD_OriginalInvestment { get; set; }
        public string LHICIC_NBV { get; set; }
        public string ESSD_NBV { get; set; }
        public string LHICIC_LatestRemodelingCost { get; set; }
        public string ESSD_LatestRemodelingCost { get; set; }
        public string TotalNetSales_Y1Projected { get; set; }
        public string SOIPct_Y1Projected { get; set; }
        public string CashFlow_Y1Projected { get; set; }
        public string McOpCoMargin_Y1Projected { get; set; }
        public string McOpCoMarginPct_Y1Projected { get; set; }
        public string SMTSize_Store { get; set; }
        public string CrewSize_Store { get; set; }
        public string TTMCrewTurnoverPct_Store { get; set; }
        public string GCPCH_Store { get; set; }
        public string TGCPCH_Store { get; set; }
        public string Mystery_Shopper_Store { get; set; }
        public string CSO_Store { get; set; }
        public string SMT_Size_Province { get; set; }
        public string CrewSize_Province { get; set; }
        public string TTMCrewTurnover_Province { get; set; }
        public string GCPCH_Province { get; set; }
        public string TGCPCH_Province { get; set; }
        public string MysteryShopper_Province { get; set; }
        public string CSO_Province { get; set; }
        public string SMTSize_National { get; set; }
        public string CrewSize_National { get; set; }
        public string TTMCrewTurnoverPct_National { get; set; }
        public string GCPCH_National { get; set; }
        public string TGCPCH_National { get; set; }
        public string MysteryShopper_National { get; set; }
        public string CSO_National { get; set; }
        public string Rent_inclAdjustment { get; set; }
        public string RentPct_inclAdjustment { get; set; }
        public string Price_Tier { get; set; }
        public string Latest_Remodeling_Date { get; set; }
        public string Market { get; set; }
        public string Pac_TTM { get; set; }
        public string Depreciation_LHI_TTM { get; set; }
        public string Interest_LHI_TTM { get; set; }
        public string Service_Fee_TTM { get; set; }
        public string Insurance_TTM { get; set; }
        public string Taxes_Licenses_TTM { get; set; }
        public string Depreciation_Essd_TTM { get; set; }
        public string Interest_Essd_TTM { get; set; }
        public string Other_Exp_TTM { get; set; }
        public string Non_Product_Sales_TTM { get; set; }
        public string Non_Product_Costs_TTM { get; set; }
        public string C_ROI_TTM { get; set; }
        public string PACPct_TTM { get; set; }
        public string PACPct_MARKET_TTM { get; set; }
        public string SOIPct_MARKET_TTM { get; set; }
        public string SOI_TTMPreviousY1 { get; set; }
        public string Cash_Flow_TTMPreviousY1 { get; set; }
        public string PAC_TTMPreviousY1 { get; set; }
        public string PACPct_MARKET_TTMPreviousY1 { get; set; }
        public string SOIPct_MARKET_TTMPreviousY1 { get; set; }
        public string SOI_TTMPreviousY2 { get; set; }
        public string Cash_Flow_TTMPreviousY2 { get; set; }
        public string PAC_TTMPreviousY2 { get; set; }
        public string PACPct_MARKET_TTMPreviousY2 { get; set; }
        public string SOIPct_MARKET_TTMPreviousY2 { get; set; }
        public string comp_sales_ttm_py1 { get; set; }
        public string comp_sales_ttm_py2 { get; set; }
        public string comp_sales_ttm { get; set; }
        public string comp_sales_market_ttm_py1 { get; set; }
        public string comp_sales_market_ttm_py2 { get; set; }
        public string comp_sales_market_ttm { get; set; }
        public string comp_gc_ttm_py1 { get; set; }
        public string comp_gc_ttm_py2 { get; set; }
        public string comp_gc_ttm { get; set; }
        public string comp_gc_market_ttm_py1 { get; set; }
        public string comp_gc_market_ttm_py2 { get; set; }
        public string comp_gc_market_ttm { get; set; }
        public string Total_Sales_TTMPY1 { get; set; }
        public string Total_Sales_TTMPY2 { get; set; }
        public string Accounting_TTM { get; set; }
        public string C_ROI_Y1 { get; set; }
        public string CASH_FLOW_TTM { get; set; }
        public string NBV_RE_COST { get; set; }
        public string Rent_TTM { get; set; }
        public string contribution_marginPct { get; set; }
    }
}
