//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class McdAMEntities : DbContext
    {
        public McdAMEntities()
            : base("name=McdAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TaskWork> TaskWork { get; set; }
        public virtual DbSet<Remind> Remind { get; set; }
        public virtual DbSet<RemindRegister> RemindRegister { get; set; }
        public virtual DbSet<ProjectIdsInfo> ProjectIdsInfo { get; set; }
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<ClosureContractRefund> ClosureContractRefund { get; set; }
        public virtual DbSet<EmployeeTitle> EmployeeTitle { get; set; }
        public virtual DbSet<MiniMarket> MiniMarket { get; set; }
        public virtual DbSet<PropertyDef> PropertyDef { get; set; }
        public virtual DbSet<PropertyValue> PropertyValue { get; set; }
        public virtual DbSet<RoleRelation> RoleRelation { get; set; }
        public virtual DbSet<EmployeeScope> EmployeeScope { get; set; }
        public virtual DbSet<MaterTrack> MaterTrack { get; set; }
        public virtual DbSet<ClosureMemoReason> ClosureMemoReason { get; set; }
        public virtual DbSet<AttachmentRequirement> AttachmentRequirement { get; set; }
        public virtual DbSet<FlowInfo> FlowInfo { get; set; }
        public virtual DbSet<NodeInfo> NodeInfo { get; set; }
        public virtual DbSet<ActionLog> ActionLog { get; set; }
        public virtual DbSet<ClosureContractInfo> ClosureContractInfo { get; set; }
        public virtual DbSet<ClosureLegalReview> ClosureLegalReview { get; set; }
        public virtual DbSet<ClosurePackage> ClosurePackage { get; set; }
        public virtual DbSet<ProjectUsers> ProjectUsers { get; set; }
        public virtual DbSet<VFlowTask> VFlowTask { get; set; }
        public virtual DbSet<NavInfo> NavInfo { get; set; }
        public virtual DbSet<MajorLeaseLegalReview> MajorLeaseLegalReviews { get; set; }
        public virtual DbSet<MajorLeaseFinancAnalysis> MajorLeaseFinancAnalysis { get; set; }
        public virtual DbSet<ReinvenstmentAmountType> ReinvenstmentAmountType { get; set; }
        public virtual DbSet<MajorLeaseConsInfo> MajorLeaseConsInfo { get; set; }
        public virtual DbSet<MajorLeaseContractInfo> MajorLeaseContractInfo { get; set; }
        public virtual DbSet<TempClosureInfo> TempClosureInfo { get; set; }
        public virtual DbSet<TempClosureLegalReview> TempClosureLegalReview { get; set; }
        public virtual DbSet<CityProvince> CityProvince { get; set; }
        public virtual DbSet<ModNoticeReceivers> ModNoticeReceivers { get; set; }
        public virtual DbSet<ModNotices> ModNotices { get; set; }
        public virtual DbSet<StartProcessLog> StartProcessLog { get; set; }
        public virtual DbSet<SysApplicationLog> SysApplicationLog { get; set; }
        public virtual DbSet<VSysRight> VSysRight { get; set; }
        public virtual DbSet<VSysRoleRight> VSysRoleRight { get; set; }
        public virtual DbSet<MajorLeaseConsInvtChecking> MajorLeaseConsInvtChecking { get; set; }
        public virtual DbSet<TempClosureMemo> TempClosureMemo { get; set; }
        public virtual DbSet<TempClosureReopenMemo> TempClosureReopenMemo { get; set; }
        public virtual DbSet<SyncRecord> SyncRecord { get; set; }
        public virtual DbSet<TempClosurePackage> TempClosurePackage { get; set; }
        public virtual DbSet<ClosureWOCheckList> ClosureWOCheckList { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreAssetHandover> DataSync_AM_PMT_StoreAssetHandover { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreAssetHandoverAttachment> DataSync_AM_PMT_StoreAssetHandoverAttachment { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreBEContractInfo> DataSync_AM_PMT_StoreBEContractInfo { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreBEInfo> DataSync_AM_PMT_StoreBEInfo { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreContractInfo> DataSync_AM_PMT_StoreContractInfo { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreContractInfoAttached> DataSync_AM_PMT_StoreContractInfoAttached { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreContractRevision> DataSync_AM_PMT_StoreContractRevision { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreMMInfo> DataSync_AM_PMT_StoreMMInfo { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreSTLicense> DataSync_AM_PMT_StoreSTLicense { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreSTLLRecord> DataSync_AM_PMT_StoreSTLLRecord { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreSTLocation> DataSync_AM_PMT_StoreSTLocation { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreSTMonthlyFinaceInfo> DataSync_AM_PMT_StoreSTMonthlyFinaceInfo { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreSTMonthlyFinaceInfoTTM> DataSync_AM_PMT_StoreSTMonthlyFinaceInfoTTM { get; set; }
        public virtual DbSet<DataSync_AM_PMT_StoreSTNegotiation> DataSync_AM_PMT_StoreSTNegotiation { get; set; }
        public virtual DbSet<DataSync_PMT_AM_Organization> DataSync_PMT_AM_Organization { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreAssetHandover> DataSync_PMT_AM_StoreAssetHandover { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreAssetHandoverAttachment> DataSync_PMT_AM_StoreAssetHandoverAttachment { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreBEContractInfo> DataSync_PMT_AM_StoreBEContractInfo { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreBEInfo> DataSync_PMT_AM_StoreBEInfo { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreContractInfo> DataSync_PMT_AM_StoreContractInfo { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreContractInfoAttached> DataSync_PMT_AM_StoreContractInfoAttached { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreContractRevision> DataSync_PMT_AM_StoreContractRevision { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreDevelop> DataSync_PMT_AM_StoreDevelop { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreMMInfo> DataSync_PMT_AM_StoreMMInfo { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreOps> DataSync_PMT_AM_StoreOps { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreSTLicense> DataSync_PMT_AM_StoreSTLicense { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreSTLLRecord> DataSync_PMT_AM_StoreSTLLRecord { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreSTLocation> DataSync_PMT_AM_StoreSTLocation { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreSTMonthlyFinaceInfo> DataSync_PMT_AM_StoreSTMonthlyFinaceInfo { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreSTMonthlyFinaceInfoTTM> DataSync_PMT_AM_StoreSTMonthlyFinaceInfoTTM { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreSTNegotiation> DataSync_PMT_AM_StoreSTNegotiation { get; set; }
        public virtual DbSet<DataSync_AM_LDW_StoreStatus> DataSync_AM_LDW_StoreStatus { get; set; }
        public virtual DbSet<DataSync_AM_PMT_SyncRecord> DataSync_AM_PMT_SyncRecord { get; set; }
        public virtual DbSet<DataSync_PMT_AM_Employee> DataSync_PMT_AM_Employee { get; set; }
        public virtual DbSet<DataSync_PMT_AM_SyncRecord> DataSync_PMT_AM_SyncRecord { get; set; }
        public virtual DbSet<DataSync_PMT_AM_SysRole> DataSync_PMT_AM_SysRole { get; set; }
        public virtual DbSet<DataSync_PMT_AM_SysRoleUserMap> DataSync_PMT_AM_SysRoleUserMap { get; set; }
        public virtual DbSet<SysRoleUserMap> SysRoleUserMap { get; set; }
        public virtual DbSet<StoreAssetHandover> StoreAssetHandover { get; set; }
        public virtual DbSet<StoreAssetHandoverAttachment> StoreAssetHandoverAttachment { get; set; }
        public virtual DbSet<StoreBEContractInfo> StoreBEContractInfo { get; set; }
        public virtual DbSet<StoreBEInfo> StoreBEInfo { get; set; }
        public virtual DbSet<StoreContractInfo> StoreContractInfo { get; set; }
        public virtual DbSet<StoreContractInfoAttached> StoreContractInfoAttached { get; set; }
        public virtual DbSet<StoreDevelop> StoreDevelop { get; set; }
        public virtual DbSet<StoreMMInfo> StoreMMInfo { get; set; }
        public virtual DbSet<StoreSTLicense> StoreSTLicense { get; set; }
        public virtual DbSet<StoreSTLLRecord> StoreSTLLRecord { get; set; }
        public virtual DbSet<StoreSTMonthlyFinaceInfo> StoreSTMonthlyFinaceInfo { get; set; }
        public virtual DbSet<StoreSTMonthlyFinaceInfoTTM> StoreSTMonthlyFinaceInfoTTM { get; set; }
        public virtual DbSet<StoreSTNegotiation> StoreSTNegotiation { get; set; }
        public virtual DbSet<StoreOps> StoreOps { get; set; }
        public virtual DbSet<SysRole> SysRole { get; set; }
        public virtual DbSet<DataSync_LDW_AM_BEInfo> DataSync_LDW_AM_BEInfo { get; set; }
        public virtual DbSet<DataSync_LDW_AM_STBEMonthSales> DataSync_LDW_AM_STBEMonthSales { get; set; }
        public virtual DbSet<DataSync_LDW_AM_STMonthlyFinaceInfo> DataSync_LDW_AM_STMonthlyFinaceInfo { get; set; }
        public virtual DbSet<ProjectContractInfo> ProjectContractInfo { get; set; }
        public virtual DbSet<ProjectStatusChangeLog> ProjectStatusChangeLog { get; set; }
        public virtual DbSet<RebuildConsInfo> RebuildConsInfo { get; set; }
        public virtual DbSet<RebuildFinancAnalysis> RebuildFinancAnalysis { get; set; }
        public virtual DbSet<RebuildInfo> RebuildInfo { get; set; }
        public virtual DbSet<RebuildLegalReview> RebuildLegalReview { get; set; }
        public virtual DbSet<RenewalInfo> RenewalInfo { get; set; }
        public virtual DbSet<ApproveDialogUser> ApproveDialogUser { get; set; }
        public virtual DbSet<DataSync_PMT_AM_Dictionary> DataSync_PMT_AM_Dictionary { get; set; }
        public virtual DbSet<Dictionary> Dictionary { get; set; }
        public virtual DbSet<RenewalLetter> RenewalLetter { get; set; }
        public virtual DbSet<RenewalLLNegotiation> RenewalLLNegotiation { get; set; }
        public virtual DbSet<RenewalLLNegotiationRecord> RenewalLLNegotiationRecord { get; set; }
        public virtual DbSet<DataSync_PMT_AM_Position> DataSync_PMT_AM_Position { get; set; }
        public virtual DbSet<DataSync_PMT_AM_SysRolePositionMap> DataSync_PMT_AM_SysRolePositionMap { get; set; }
        public virtual DbSet<DataSync_PMT_AM_UserData> DataSync_PMT_AM_UserData { get; set; }
        public virtual DbSet<RenewalConsInfo> RenewalConsInfo { get; set; }
        public virtual DbSet<ReimageSummary> ReimageSummary { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<PositionScopeMap> PositionScopeMap { get; set; }
        public virtual DbSet<SysRolePositionMap> SysRolePositionMap { get; set; }
        public virtual DbSet<LDW_FinanceData> LDW_FinanceData { get; set; }
        public virtual DbSet<ReimageConsInfo> ReimageConsInfo { get; set; }
        public virtual DbSet<RenewalTool> RenewalTool { get; set; }
        public virtual DbSet<RenewalToolWriteOffAndReinCost> RenewalToolWriteOffAndReinCost { get; set; }
        public virtual DbSet<RebuildConsInvtChecking> RebuildConsInvtChecking { get; set; }
        public virtual DbSet<ReimageConsInvtChecking> ReimageConsInvtChecking { get; set; }
        public virtual DbSet<RenewalPackage> RenewalPackage { get; set; }
        public virtual DbSet<EstimatedVsActualConstruction> EstimatedVsActualConstruction { get; set; }
        public virtual DbSet<RenewalLegalApproval> RenewalLegalApproval { get; set; }
        public virtual DbSet<ReimagePackage> ReimagePackage { get; set; }
        public virtual DbSet<DataSync_LDW_AM_STFinanceData> DataSync_LDW_AM_STFinanceData { get; set; }
        public virtual DbSet<SysUserMMMap> SysUserMMMap { get; set; }
        public virtual DbSet<NotificationMessage> NotificationMessage { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<ProjectComment> ProjectComment { get; set; }
        public virtual DbSet<ReimageInfo> ReimageInfo { get; set; }
        public virtual DbSet<AttachmentsMemo> AttachmentsMemo { get; set; }
        public virtual DbSet<AttachmentsMemoProcessInfo> AttachmentsMemoProcessInfo { get; set; }
        public virtual DbSet<RenewalAnalysis> RenewalAnalysis { get; set; }
        public virtual DbSet<StoreCM> StoreCM { get; set; }
        public virtual DbSet<ReinvestmentBasicInfo> ReinvestmentBasicInfo { get; set; }
        public virtual DbSet<RebuildPackage> RebuildPackage { get; set; }
        public virtual DbSet<StoreProfitabilityAndLeaseInfo> StoreProfitabilityAndLeaseInfo { get; set; }
        public virtual DbSet<StoreSTLocation> StoreSTLocation { get; set; }
        public virtual DbSet<ProjectContractRevision> ProjectContractRevision { get; set; }
        public virtual DbSet<StoreContractRevision> StoreContractRevision { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<MajorLeaseChangePackage> MajorLeaseChangePackage { get; set; }
        public virtual DbSet<RPFieldSetting> RPFieldSetting { get; set; }
        public virtual DbSet<RPSelectionSetting> RPSelectionSetting { get; set; }
        public virtual DbSet<RPTableSetting> RPTableSetting { get; set; }
        public virtual DbSet<RPTemplate> RPTemplate { get; set; }
        public virtual DbSet<ClosureConsInvtChecking> ClosureConsInvtChecking { get; set; }
        public virtual DbSet<GBMemo> GBMemo { get; set; }
        public virtual DbSet<MajorLeaseGBMemo> MajorLeaseGBMemo { get; set; }
        public virtual DbSet<ReimageGBMemo> ReimageGBMemo { get; set; }
        public virtual DbSet<RenewalGBMemo> RenewalGBMemo { get; set; }
        public virtual DbSet<ReopenMemo> ReopenMemo { get; set; }
        public virtual DbSet<StoreSTLocationHistory> StoreSTLocationHistory { get; set; }
        public virtual DbSet<FinancialPreanalysis> FinancialPreanalysis { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<ClosureToolImpactOtherStore> ClosureToolImpactOtherStore { get; set; }
        public virtual DbSet<VProjectComment> VProjectComment { get; set; }
        public virtual DbSet<MajorLeaseInfo> MajorLeaseInfo { get; set; }
        public virtual DbSet<StoreBasicInfo> StoreBasicInfo { get; set; }
        public virtual DbSet<DataSync_PMT_AM_StoreBasicInfo> DataSync_PMT_AM_StoreBasicInfo { get; set; }
        public virtual DbSet<ReinvestmentCost> ReinvestmentCost { get; set; }
        public virtual DbSet<WriteOffAmount> WriteOffAmount { get; set; }
        public virtual DbSet<RPTemplateFieldDetail> RPTemplateFieldDetail { get; set; }
        public virtual DbSet<RPTemplateTableDetail> RPTemplateTableDetail { get; set; }
        public virtual DbSet<ClosureTool> ClosureTool { get; set; }
        public virtual DbSet<HoldingStatusChangeLog> HoldingStatusChangeLog { get; set; }
        public virtual DbSet<ScheduleLog> ScheduleLog { get; set; }
        public virtual DbSet<ClosureExecutiveSummary> ClosureExecutiveSummary { get; set; }
        public virtual DbSet<ClosureInfo> ClosureInfo { get; set; }
        public virtual DbSet<ProjectInfo> ProjectInfo { get; set; }
        public virtual DbSet<V_AM_DL_Closure> V_AM_DL_Closure { get; set; }
        public virtual DbSet<V_AM_DL_Reimage> V_AM_DL_Reimage { get; set; }
        public virtual DbSet<RenewalClearanceReport> RenewalClearanceReport { get; set; }
        public virtual DbSet<RenewalConfirmLetter> RenewalConfirmLetter { get; set; }
        public virtual DbSet<RenewalToolFinMeasureOutput> RenewalToolFinMeasureOutput { get; set; }
        public virtual DbSet<ProjectNode> ProjectNode { get; set; }
        public virtual DbSet<VProjectNode> VProjectNode { get; set; }
        public virtual DbSet<ProjectProgress> ProjectProgress { get; set; }
        public virtual DbSet<NecessaryNoticeConfig> NecessaryNoticeConfig { get; set; }
        public virtual DbSet<DataSync_LDW_AM_STFinanceData2> DataSync_LDW_AM_STFinanceData2 { get; set; }
        public virtual DbSet<VProject> VProject { get; set; }
        public virtual DbSet<ClosureMemo> ClosureMemo { get; set; }
        public virtual DbSet<V_AM_DL_MajorLeaseChange> V_AM_DL_MajorLeaseChange { get; set; }
        public virtual DbSet<V_AM_DL_Rebuild> V_AM_DL_Rebuild { get; set; }
        public virtual DbSet<V_AM_DL_Renewal> V_AM_DL_Renewal { get; set; }
        public virtual DbSet<VStoreList> VStoreList { get; set; }
        public virtual DbSet<RenewalToolFinMeasureInput> RenewalToolFinMeasureInput { get; set; }
    
        public virtual int Proc_SearchEmployee(string name, string code, string positionCodes, string storeCode, Nullable<int> pageIndex, Nullable<int> pageSize, string order, ObjectParameter totalRecords)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var positionCodesParameter = positionCodes != null ?
                new ObjectParameter("positionCodes", positionCodes) :
                new ObjectParameter("positionCodes", typeof(string));
    
            var storeCodeParameter = storeCode != null ?
                new ObjectParameter("storeCode", storeCode) :
                new ObjectParameter("storeCode", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("pageIndex", pageIndex) :
                new ObjectParameter("pageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var orderParameter = order != null ?
                new ObjectParameter("order", order) :
                new ObjectParameter("order", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_SearchEmployee", nameParameter, codeParameter, positionCodesParameter, storeCodeParameter, pageIndexParameter, pageSizeParameter, orderParameter, totalRecords);
        }
    
        public virtual ObjectResult<Proc_GetProjectProcess_Result> Proc_GetProjectProcess(string projectId)
        {
            var projectIdParameter = projectId != null ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetProjectProcess_Result>("Proc_GetProjectProcess", projectIdParameter);
        }
    
        public virtual int Proc_AutoExecute()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_AutoExecute");
        }
    
        public virtual int Proc_GenerateClosureConsInvtChecking()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GenerateClosureConsInvtChecking");
        }
    
        public virtual int Proc_GenerateClosureMemoTask()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GenerateClosureMemoTask");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Proc_ProjectHistory_Result> Proc_GetProjectHistory(string projectId, string tableName, Nullable<bool> hasTemplate)
        {
            var projectIdParameter = projectId != null ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(string));
    
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            var hasTemplateParameter = hasTemplate.HasValue ?
                new ObjectParameter("hasTemplate", hasTemplate) :
                new ObjectParameter("hasTemplate", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ProjectHistory_Result>("Proc_GetProjectHistory", projectIdParameter, tableNameParameter, hasTemplateParameter);
        }
    
        public virtual int proc_DataSync_AM_ILDB_All_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_All_Set");
        }
    
        public virtual int proc_DataSync_AM_ILDB_StoreAssetHandover_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_StoreAssetHandover_Set");
        }
    
        public virtual int proc_DataSync_AM_ILDB_StoreAssetHandoverAttachment_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_StoreAssetHandoverAttachment_Set");
        }
    
        public virtual int proc_DataSync_AM_ILDB_StoreBEContractInfo_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_StoreBEContractInfo_Set");
        }
    
        public virtual int proc_DataSync_AM_ILDB_StoreBEInfo_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_StoreBEInfo_Set");
        }
    
        public virtual int proc_DataSync_AM_ILDB_StoreContractInfo_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_StoreContractInfo_Set");
        }
    
        public virtual int proc_DataSync_AM_ILDB_StoreContractInfoAttached_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_StoreContractInfoAttached_Set");
        }
    
        public virtual int proc_DataSync_AM_ILDB_StoreContractRevision_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_StoreContractRevision_Set");
        }
    
        public virtual int proc_DataSync_AM_ILDB_StoreMMInfo_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_StoreMMInfo_Set");
        }
    
        public virtual int proc_DataSync_AM_ILDB_StoreSTLicense_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_StoreSTLicense_Set");
        }
    
        public virtual int proc_DataSync_AM_ILDB_StoreSTLLRecord_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_StoreSTLLRecord_Set");
        }
    
        public virtual int proc_DataSync_AM_ILDB_StoreSTLocation_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_StoreSTLocation_Set");
        }
    
        public virtual int proc_DataSync_AM_ILDB_StoreSTNegotiation_Set()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_ILDB_StoreSTNegotiation_Set");
        }
    
        public virtual int proc_DataSync_AM_PMT_GETALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_PMT_GETALL");
        }
    
        public virtual int proc_DataSync_AM_PMT_StoreBEContractInfo_Get(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_PMT_StoreBEContractInfo_Get", dBNameParameter);
        }
    
        public virtual int proc_DataSync_AM_PMT_StoreBEInfo_Get(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_PMT_StoreBEInfo_Get", dBNameParameter);
        }
    
        public virtual int proc_DataSync_AM_PMT_StoreContractInfo_Get(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_PMT_StoreContractInfo_Get", dBNameParameter);
        }
    
        public virtual int proc_DataSync_AM_PMT_StoreContractInfoAttached_Get(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_PMT_StoreContractInfoAttached_Get", dBNameParameter);
        }
    
        public virtual int proc_DataSync_AM_PMT_StoreContractRevision_Get(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_PMT_StoreContractRevision_Get", dBNameParameter);
        }
    
        public virtual int proc_DataSync_AM_PMT_StoreMMInfo_Get(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_PMT_StoreMMInfo_Get", dBNameParameter);
        }
    
        public virtual int proc_DataSync_AM_PMT_StoreSTLicense_Get(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_PMT_StoreSTLicense_Get", dBNameParameter);
        }
    
        public virtual int proc_DataSync_AM_PMT_StoreSTLLRecord_Get(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_PMT_StoreSTLLRecord_Get", dBNameParameter);
        }
    
        public virtual int proc_DataSync_AM_PMT_StoreSTLocation_Get(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_PMT_StoreSTLocation_Get", dBNameParameter);
        }
    
        public virtual int proc_DataSync_AM_PMT_StoreSTNegotiation_Get(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_AM_PMT_StoreSTNegotiation_Get", dBNameParameter);
        }
    
        public virtual int proc_DataSync_FROM_AM_TO_PMT_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_FROM_AM_TO_PMT_All");
        }
    
        public virtual int proc_DataSync_FROM_PMT_TO_AM_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_FROM_PMT_TO_AM_All");
        }
    
        public virtual int proc_DataSync_FROM_PMT_TO_AM_Employee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_FROM_PMT_TO_AM_Employee");
        }
    
        public virtual int proc_DataSync_ILDB_AM_All_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_All_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_Employee_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_Employee_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_Organization_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_Organization_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreAssetHandover_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreAssetHandover_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreAssetHandoverAttachment_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreAssetHandoverAttachment_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreBasicInfo_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreBasicInfo_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreBEContractInfo_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreBEContractInfo_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreBEInfo_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreBEInfo_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreContractInfo_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreContractInfo_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreContractInfoAttached_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreContractInfoAttached_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreContractRevision_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreContractRevision_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreDevelop_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreDevelop_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreMMInfo_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreMMInfo_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreOps_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreOps_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreSTLicense_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreSTLicense_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreSTLLRecord_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreSTLLRecord_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreSTLocation_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreSTLocation_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreSTMonthlyFinaceInfo_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreSTMonthlyFinaceInfo_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreSTMonthlyFinaceInfoTTM_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreSTMonthlyFinaceInfoTTM_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_StoreSTNegotiation_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_StoreSTNegotiation_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_SysRole_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_SysRole_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_SysRoleUserMap_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_SysRoleUserMap_Get");
        }
    
        public virtual int proc_DataSync_LDW_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_LDW_All");
        }
    
        public virtual int proc_DataSync_LDW_AM_BEInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_LDW_AM_BEInfo");
        }
    
        public virtual int proc_DataSync_LDW_AM_STBEMonthSales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_LDW_AM_STBEMonthSales");
        }
    
        public virtual int proc_DataSync_LDW_AM_STFinanceData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_LDW_AM_STFinanceData");
        }
    
        public virtual int proc_DataSync_LDW_AM_STFinanceData2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_LDW_AM_STFinanceData2");
        }
    
        public virtual int proc_DataSync_LDW_AM_STMonthlyFinaceInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_LDW_AM_STMonthlyFinaceInfo");
        }
    
        public virtual int proc_DataSync_PMT_AM_Employee_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_Employee_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_Organization_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_Organization_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_SETALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_SETALL");
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreAssetHandover_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreAssetHandover_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreAssetHandoverAttachment_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreAssetHandoverAttachment_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreBasicInfo_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreBasicInfo_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreBEContractInfo_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreBEContractInfo_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreBEInfo_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreBEInfo_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreContractInfo_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreContractInfo_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreContractInfoAttached_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreContractInfoAttached_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreContractRevision_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreContractRevision_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreDevelop_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreDevelop_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreMMInfo_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreMMInfo_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreOps_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreOps_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreSTLicense_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreSTLicense_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreSTLLRecord_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreSTLLRecord_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreSTLocation_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreSTLocation_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreSTMonthlyFinaceInfo_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreSTMonthlyFinaceInfo_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreSTMonthlyFinaceInfoTTM_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreSTMonthlyFinaceInfoTTM_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_StoreSTNegotiation_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_StoreSTNegotiation_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_SysRole_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_SysRole_Set", dBNameParameter);
        }
    
        public virtual int proc_DataSync_PMT_AM_SysRoleUserMap_Set(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_PMT_AM_SysRoleUserMap_Set", dBNameParameter);
        }
    
        public virtual int Proc_GenerateClosureConsInvtChecking_New()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GenerateClosureConsInvtChecking_New");
        }
    
        public virtual ObjectResult<proc_TtmhistoricalFinancialData_Result> proc_TtmhistoricalFinancialData(string usCode)
        {
            var usCodeParameter = usCode != null ?
                new ObjectParameter("UsCode", usCode) :
                new ObjectParameter("UsCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_TtmhistoricalFinancialData_Result>("proc_TtmhistoricalFinancialData", usCodeParameter);
        }
    
        public virtual ObjectResult<Proc_PrepareClosureMemo_Result> Proc_PrepareClosureMemo(string projectId)
        {
            var projectIdParameter = projectId != null ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_PrepareClosureMemo_Result>("Proc_PrepareClosureMemo", projectIdParameter);
        }
    
        public virtual int proc_DataSync_ILDB_AM_Dictionary_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_Dictionary_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_Position_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_Position_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_SysRolePositionMap_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_SysRolePositionMap_Get");
        }
    
        public virtual int proc_DataSync_ILDB_AM_UserData_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DataSync_ILDB_AM_UserData_Get");
        }
    
        public virtual int Proc_LDW_UpdateStoreStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_LDW_UpdateStoreStatus");
        }
    
        public virtual ObjectResult<Proc_SearchStoreEmployeeByRoleID_Result> Proc_SearchStoreEmployeeByRoleID(Nullable<int> roleID, string storeCode)
        {
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("roleID", roleID) :
                new ObjectParameter("roleID", typeof(int));
    
            var storeCodeParameter = storeCode != null ?
                new ObjectParameter("storeCode", storeCode) :
                new ObjectParameter("storeCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_SearchStoreEmployeeByRoleID_Result>("Proc_SearchStoreEmployeeByRoleID", roleIDParameter, storeCodeParameter);
        }
    
        [DbFunction("McdAMEntities", "Uf_GetChildOrg")]
        public virtual IQueryable<Uf_GetChildOrg_Result> Uf_GetChildOrg(string parentID)
        {
            var parentIDParameter = parentID != null ?
                new ObjectParameter("ParentID", parentID) :
                new ObjectParameter("ParentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Uf_GetChildOrg_Result>("[McdAMEntities].[Uf_GetChildOrg](@ParentID)", parentIDParameter);
        }
    }
}
