//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public int Id { get; set; }
        public string NameZHCN { get; set; }
        public string NameENUS { get; set; }
        public string Value { get; set; }
        public string Code { get; set; }
        public string ParentCode { get; set; }
        public Nullable<int> Type_ID { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDirectory { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUserAccount { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public int Sequence { get; set; }
        public string ExtendField0 { get; set; }
        public string ExtendField1 { get; set; }
        public string ExtendField2 { get; set; }
        public string ExtendField3 { get; set; }
        public string ExtendField4 { get; set; }
        public string ExtendField5 { get; set; }
    }
}
