//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimatedVsActualConstruction
    {
        public int Id { get; set; }
        public Nullable<System.Guid> RefId { get; set; }
        public Nullable<System.DateTime> GBDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string ClosureDays { get; set; }
        public string OriginalOperationSize { get; set; }
        public string OriginalSeatNumber { get; set; }
        public string ARDC { get; set; }
        public string NewOperationSize { get; set; }
        public string ARSN { get; set; }
        public string ARPT { get; set; }
        public Nullable<System.DateTime> ActualGBDate { get; set; }
        public Nullable<System.DateTime> ActualCompletionDate { get; set; }
        public string ActualClosureDays { get; set; }
    }
}
