//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    
    public enum FieldConditionType : int
    {
        None = 0,
        String = 1,
        Date = 2,
        Number = 3,
        Dictionary = 4,
        Money = 5,
        Percent = 6,
        Boolean = 7
    }
}
