//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialPreanalysis
    {
        public int Id { get; set; }
        public System.Guid RefId { get; set; }
        public Nullable<decimal> TTMSales { get; set; }
        public string NewAddBE { get; set; }
        public string StoreCM { get; set; }
        public string ReimagePrice { get; set; }
        public string ReimagePriceSales { get; set; }
        public Nullable<bool> IsMcCafe { get; set; }
        public string McCafe { get; set; }
        public string McCafeSales { get; set; }
        public Nullable<bool> IsKiosk { get; set; }
        public string Kiosk { get; set; }
        public string KioskSales { get; set; }
        public Nullable<bool> IsMDS { get; set; }
        public string MDS { get; set; }
        public string MDSSales { get; set; }
        public Nullable<bool> IsTwientyFourHour { get; set; }
        public string TwientyFourHour { get; set; }
        public string TwientyFourHourSales { get; set; }
        public string TotalSalesInc { get; set; }
        public string IncSales { get; set; }
        public string MarginInc { get; set; }
        public string SalesBuildingInvestment { get; set; }
        public string NoneSalesBuildingInvst { get; set; }
        public string IINB { get; set; }
        public string ROI { get; set; }
        public string PaybackYears { get; set; }
        public string EstimatedWriteOffCost { get; set; }
        public string ISDWIP { get; set; }
        public string CurrentPriceTier { get; set; }
        public string SPTAR { get; set; }
        public string PriceTierafterReimage { get; set; }
        public string YearMonth { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
    }
}
