//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDW_FinanceData
    {
        public int FinanceDataID { get; set; }
        public string ProjectId { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string UsCode { get; set; }
        public string FinanceYear { get; set; }
        public string FinanceMonth { get; set; }
        public string Total_Sales_TTM { get; set; }
        public string comp_sales_ttm { get; set; }
        public string comp_sales_market_ttm { get; set; }
        public string comp_gc_ttm { get; set; }
        public string comp_gc_market_ttm { get; set; }
        public string Pac_TTM { get; set; }
        public string PACPct_TTM { get; set; }
        public string PACPct_MARKET_TTM { get; set; }
        public string Rent_TTM { get; set; }
        public string Depreciation_LHI_TTM { get; set; }
        public string Service_Fee_TTM { get; set; }
        public string Accounting_TTM { get; set; }
        public string Insurance_TTM { get; set; }
        public string Taxes_Licenses_TTM { get; set; }
        public string Depreciation_Essd_TTM { get; set; }
        public string Interest_Essd_TTM { get; set; }
        public string Other_Exp_TTM { get; set; }
        public string ProductSales_TTM { get; set; }
        public string Non_Product_Sales_TTM { get; set; }
        public string Non_Product_Costs_TTM { get; set; }
        public string SOIPct_TTM { get; set; }
        public string SOIPct_MARKET_TTM { get; set; }
        public string CashFlow_TTM { get; set; }
        public string Total_Sales_TTMPY1 { get; set; }
        public string Total_Sales_TTMPY2 { get; set; }
        public string comp_sales_ttm_py1 { get; set; }
        public string comp_sales_ttm_py2 { get; set; }
        public string comp_sales_market_ttm_py1 { get; set; }
        public string comp_sales_market_ttm_py2 { get; set; }
        public string comp_gc_ttm_py1 { get; set; }
        public string comp_gc_ttm_py2 { get; set; }
        public string comp_gc_market_ttm_py1 { get; set; }
        public string comp_gc_market_ttm_py2 { get; set; }
        public string PAC_TTMPreviousY1 { get; set; }
        public string PAC_TTMPreviousY2 { get; set; }
        public string PACPct_MARKET_TTMPreviousY1 { get; set; }
        public string PACPct_MARKET_TTMPreviousY2 { get; set; }
        public string SOI_TTMPreviousY1 { get; set; }
        public string SOI_TTMPreviousY2 { get; set; }
        public string SOIPct_MARKET_TTMPreviousY1 { get; set; }
        public string SOIPct_MARKET_TTMPreviousY2 { get; set; }
        public string Cash_Flow_TTMPreviousY1 { get; set; }
        public string Cash_Flow_TTMPreviousY2 { get; set; }
        public string Interest_LHI_TTM { get; set; }
        public Nullable<System.Guid> RefTableId { get; set; }
    }
}
