//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MajorLeaseInfo
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public string USCode { get; set; }
        public Nullable<System.DateTime> GBDate { get; set; }
        public Nullable<System.DateTime> ReopenDate { get; set; }
        public Nullable<bool> ChangeRentalType { get; set; }
        public string ChangeRentalTypeDESC { get; set; }
        public Nullable<bool> ChangeRedLineType { get; set; }
        public string ChangeRedLineTypeDESC { get; set; }
        public Nullable<bool> ChangeLeaseTermType { get; set; }
        public string ChangeLeaseTermDESC { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateUserNameZHCN { get; set; }
        public string CreateUserNameENUS { get; set; }
        public string AssetRepAccount { get; set; }
        public string AssetRepNameZHCN { get; set; }
        public string AssetRepNameENUS { get; set; }
        public string AssetActorAccount { get; set; }
        public string AssetActorNameZHCN { get; set; }
        public string AssetActorNameENUS { get; set; }
        public string FinanceAccount { get; set; }
        public string FinanceNameZHCN { get; set; }
        public string FinanceNameENUS { get; set; }
        public string PMAccount { get; set; }
        public string PMNameZHCN { get; set; }
        public string PMNameENUS { get; set; }
        public string LegalAccount { get; set; }
        public string LegalNameZHCN { get; set; }
        public string LegalNameENUS { get; set; }
        public string StoreNameENUS { get; set; }
        public string StoreNameZHCN { get; set; }
        public string AssetManagerAccount { get; set; }
        public string AssetManagerNameZHCN { get; set; }
        public string AssetManagerNameENUS { get; set; }
        public string CMAccount { get; set; }
        public string CMNameZHCN { get; set; }
        public string CMNameENUS { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> ChangeLandlordType { get; set; }
        public string ChangeLandLordDESC { get; set; }
        public Nullable<bool> ChangeOtherType { get; set; }
        public string ChangeOthersDESC { get; set; }
        public string OldRentalStructure { get; set; }
        public string NewRentalStructure { get; set; }
        public Nullable<decimal> OldChangeRedLineRedLineArea { get; set; }
        public Nullable<decimal> NewChangeRedLineRedLineArea { get; set; }
        public Nullable<System.DateTime> OldChangeLeaseTermExpiraryDate { get; set; }
        public Nullable<System.DateTime> NewChangeLeaseTermExpiraryDate { get; set; }
        public string OldLandlord { get; set; }
        public string NewLandlord { get; set; }
        public string Others { get; set; }
        public string LeaseChangeDescription { get; set; }
    }
}
