//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterTrack
    {
        public System.Guid Id { get; set; }
        public string WorkflowId { get; set; }
        public string WorkflowType { get; set; }
        public System.Guid NodeId { get; set; }
        public string NodeType { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid Creator { get; set; }
        public string CreatorZHCN { get; set; }
        public string CreatorENUS { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public MaterTrackType TrackType { get; set; }
    }
}
