//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModNoticeReceivers
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> NoticeId { get; set; }
        public string ReceiverType { get; set; }
        public string Receiver { get; set; }
        public string ReceiverENUS { get; set; }
        public string ReceiverZHCN { get; set; }
        public Nullable<int> IsReaded { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
