//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModNotices
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string RefId { get; set; }
        public string RefTableName { get; set; }
        public string ProcessId { get; set; }
        public string StoreCode { get; set; }
        public string ProcInstID { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreateUserAccount { get; set; }
        public string SenderAccount { get; set; }
        public string SenderNameENUS { get; set; }
        public string SenderNameZHCN { get; set; }
    }
}
