//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavInfo
    {
        public System.Guid Id { get; set; }
        public string Href { get; set; }
        public string DispZHCN { get; set; }
        public string DispENUS { get; set; }
        public string FlowCode { get; set; }
        public string SubFlowCode { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public string CreateUserAccount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Disq { get; set; }
    }
}
