//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeInfo
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public Nullable<double> ProgressRate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserAccount { get; set; }
        public string FlowCode { get; set; }
        public string NameZHCN { get; set; }
        public string NameENUS { get; set; }
        public Nullable<NodeType> Type { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string TemplateZHCN { get; set; }
        public string TemplateENUS { get; set; }
        public bool ClearStatus { get; set; }
    }
}
