//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public System.Guid RefId { get; set; }
        public string ProjectId { get; set; }
        public string SenderCode { get; set; }
        public string ReceiverCode { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string CreateUserAccount { get; set; }
        public bool IsSendEmail { get; set; }
        public bool HasRead { get; set; }
        public string FlowCode { get; set; }
        public Nullable<System.Guid> ContentId { get; set; }
        public string Title { get; set; }
        public int Id { get; set; }
    }
}
