//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    
    public enum ProjectStatus : int
    {
        UnFinish = 0,
        Finished = 2,
        Pending = 3,
        Rejected = 4,
        Completed = 5,
        Recalled = 6,
        Killed = 7,
        UnKnown = -1
    }
}
