//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    
    public enum ProjectNodeStatus : int
    {
        UnKnown = 0,
        UnFinish = 1,
        Finish = 2,
        Pending = 3
    }
}
