//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUsers
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public string UserAccount { get; set; }
        public string RoleCode { get; set; }
        public string RoleNameZHCN { get; set; }
        public string RoleNameENUS { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string UserNameZHCN { get; set; }
        public string UserNameENUS { get; set; }
    }
}
