//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public System.Guid Id { get; set; }
        public string FlowCode { get; set; }
        public string FlowNameZHCN { get; set; }
        public string FlowNameENUS { get; set; }
        public string ProjectId { get; set; }
        public string USCode { get; set; }
        public string NodeNameZHCN { get; set; }
        public string NodeNameENUS { get; set; }
        public string NodeCode { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public ProjectStatus Status { get; set; }
        public string CreateUserAccount { get; set; }
        public Nullable<bool> IsPushed { get; set; }
    }
}
