//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remind
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string RegisterCode { get; set; }
        public string Content { get; set; }
        public string ReceiverAccount { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUserAccount { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string SenderAccount { get; set; }
        public bool IsReaded { get; set; }
        public string ReceiverNameZHCN { get; set; }
        public string ReceiverNameENUS { get; set; }
        public string SenderNameENUS { get; set; }
        public string SenderNameZHCN { get; set; }
        public string Url { get; set; }
    }
}
