//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenewalToolFinMeasureOutput
    {
        public System.Guid Id { get; set; }
        public System.Guid ToolId { get; set; }
        public Nullable<decimal> AnnualRentExpenseLY { get; set; }
        public Nullable<decimal> AnnualRentExpenseYr1 { get; set; }
        public Nullable<decimal> AnnualRentExpenseAvg { get; set; }
        public Nullable<decimal> RentAsProdSalesLY { get; set; }
        public Nullable<decimal> RentAsProdSalesYr1 { get; set; }
        public Nullable<decimal> RentAsProdSalesAvg { get; set; }
        public Nullable<decimal> OccupancyProdSalesLY { get; set; }
        public Nullable<decimal> OccupancyProdSalesYr1 { get; set; }
        public Nullable<decimal> OccupancyProdSalesAvg { get; set; }
        public Nullable<decimal> SOIProdSalesLY { get; set; }
        public Nullable<decimal> SOIProdSalesYr1 { get; set; }
        public Nullable<decimal> SOIProdSalesAvg { get; set; }
        public Nullable<decimal> CashROILY { get; set; }
        public Nullable<decimal> CashROIYr1 { get; set; }
        public Nullable<decimal> CashROIAvg { get; set; }
    }
}
