//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成�?
//
//     手动更改此文件可能导致应用程序出现意外的行为�?
//     如果重新生成代码，将覆盖对此文件的手动更改�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenewalInfo
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public string USCode { get; set; }
        public string StoreNameZHCN { get; set; }
        public string StoreNameENUS { get; set; }
        public string Priority { get; set; }
        public double RenewalYears { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUserAccount { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public string ModifyUserAccount { get; set; }
        public string AssetRepAccount { get; set; }
        public string AssetRepNameZHCN { get; set; }
        public string AssetRepNameENUS { get; set; }
        public string AssetActorAccount { get; set; }
        public string AssetActorNameZHCN { get; set; }
        public string AssetActorNameENUS { get; set; }
        public string FinanceAccount { get; set; }
        public string FinanceNameZHCN { get; set; }
        public string FinanceNameENUS { get; set; }
        public string PMAccount { get; set; }
        public string PMNameZHCN { get; set; }
        public string PMNameENUS { get; set; }
        public string LegalAccount { get; set; }
        public string LegalNameZHCN { get; set; }
        public string LegalNameENUS { get; set; }
        public string AssetManagerAccount { get; set; }
        public string AssetManagerNameZHCN { get; set; }
        public string AssetManagerNameENUS { get; set; }
        public string CMAccount { get; set; }
        public string CMNameZHCN { get; set; }
        public string CMNameENUS { get; set; }
        public bool NeedProjectCostEst { get; set; }
        public Nullable<System.DateTime> NewLeaseStartDate { get; set; }
        public Nullable<System.DateTime> NewLeaseEndDate { get; set; }
    }
}
