//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenewalAnalysis
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public Nullable<int> ProcInstId { get; set; }
        public string TADesirability { get; set; }
        public string MMTADescription { get; set; }
        public string MMTADescriptionNew { get; set; }
        public string MajorGenerators { get; set; }
        public string MajorGeneratorsNew { get; set; }
        public string SiteRERating { get; set; }
        public string SiteDescription { get; set; }
        public string LeasedArea { get; set; }
        public string OperationSize { get; set; }
        public string Floors { get; set; }
        public string Seats { get; set; }
        public string BEType { get; set; }
        public string LeaseTenureAndTerm { get; set; }
        public string FreeRentalPeriod { get; set; }
        public string RentStructure { get; set; }
        public string MFStructure { get; set; }
        public string MFStructureNew { get; set; }
        public Nullable<decimal> DRMF1stTY { get; set; }
        public Nullable<decimal> DRMF1stTYSales { get; set; }
        public Nullable<decimal> FairMarketRentAmount { get; set; }
        public Nullable<decimal> FairMarketRentAgent { get; set; }
        public Nullable<decimal> DR1stTYAmount { get; set; }
        public Nullable<decimal> RentDeviation { get; set; }
        public Nullable<decimal> AnnualSOILastTY { get; set; }
        public Nullable<decimal> CashROILastTY { get; set; }
        public string LastRemodeling { get; set; }
        public string LastRemodelingNew { get; set; }
        public string OriginalInvestmentNew { get; set; }
        public string ExclusivityClauseNew { get; set; }
        public string McDsEarlyTerminationRightNew { get; set; }
        public string McDsEPRight { get; set; }
        public string McDsEPRightNew { get; set; }
        public string LandlordEntityNew { get; set; }
        public string SpecialClauses { get; set; }
        public string SpecialClausesNew { get; set; }
        public string OtherIssues { get; set; }
        public string OtherIssuesNew { get; set; }
        public string CreateUserAccount { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string LastUpdateUserAccount { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public bool IsHistory { get; set; }
        public string DecisionLogic { get; set; }
        public string SpecialApprovalRequired { get; set; }
        public Nullable<decimal> DRMFLastTY { get; set; }
        public Nullable<decimal> DRMFLastTYSales { get; set; }
    }
}
