//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenewalToolFinMeasureInput
    {
        public System.Guid Id { get; set; }
        public System.Guid ToolId { get; set; }
        public string RentalStructure { get; set; }
        public Nullable<decimal> ContributionMargin { get; set; }
        public System.DateTime DataRecordTime { get; set; }
        public Nullable<decimal> ProductSalesOriginal { get; set; }
        public Nullable<decimal> ProductSalesAdjustment { get; set; }
        public Nullable<decimal> PacOriginal { get; set; }
        public Nullable<decimal> PacAdjustment { get; set; }
        public Nullable<decimal> CompSalesOriginal { get; set; }
        public Nullable<decimal> CompSalesAdjustment { get; set; }
        public Nullable<decimal> RentOriginal { get; set; }
        public Nullable<decimal> RentAdjustment { get; set; }
        public Nullable<decimal> DepreciationLhiOriginal { get; set; }
        public Nullable<decimal> DepreciationLhiAdjustment { get; set; }
        public Nullable<decimal> InterestLhiOriginal { get; set; }
        public Nullable<decimal> InterestLhiAdjustment { get; set; }
        public Nullable<decimal> ServiceFeeOriginal { get; set; }
        public Nullable<decimal> ServiceFeeAdjustment { get; set; }
        public Nullable<decimal> AccountingOriginal { get; set; }
        public Nullable<decimal> AccountingAdjustment { get; set; }
        public Nullable<decimal> InsuranceOriginal { get; set; }
        public Nullable<decimal> InsuranceAdjustment { get; set; }
        public Nullable<decimal> TaxesAndLicensesOriginal { get; set; }
        public Nullable<decimal> TaxesAndLicensesAdjustment { get; set; }
        public Nullable<decimal> DepreciationEssdOriginal { get; set; }
        public Nullable<decimal> DepreciationEssdAdjustment { get; set; }
        public Nullable<decimal> InterestEssdOriginal { get; set; }
        public Nullable<decimal> InterestEssdAdjustment { get; set; }
        public Nullable<decimal> OtherIncExpOriginal { get; set; }
        public Nullable<decimal> OtherIncExpAdjustment { get; set; }
        public Nullable<decimal> NonProductSalesOriginal { get; set; }
        public Nullable<decimal> NonProductSalesAdjustment { get; set; }
        public Nullable<decimal> NonProductCostsOriginal { get; set; }
        public Nullable<decimal> NonProductCostsAdjustment { get; set; }
        public Nullable<decimal> SalesCompYr1 { get; set; }
        public Nullable<decimal> SalesCompYr2 { get; set; }
        public Nullable<decimal> SalesCompYr3 { get; set; }
        public Nullable<decimal> SalesCompYr4 { get; set; }
        public Nullable<decimal> SalesCompYr5 { get; set; }
        public Nullable<decimal> SalesCompYr6 { get; set; }
        public Nullable<decimal> SalesCompYr7 { get; set; }
        public Nullable<decimal> SalesCompYr8 { get; set; }
        public Nullable<decimal> SalesCompYr9 { get; set; }
        public Nullable<decimal> SalesCompYr10 { get; set; }
        public Nullable<decimal> SalesCompYr11 { get; set; }
        public Nullable<decimal> SalesCompYr12 { get; set; }
        public Nullable<decimal> SalesCompYr13 { get; set; }
        public Nullable<decimal> SalesCompYr14 { get; set; }
        public Nullable<decimal> SalesCompYr15 { get; set; }
        public Nullable<decimal> SalesCompYr16 { get; set; }
        public Nullable<decimal> SalesCompYr17 { get; set; }
        public Nullable<decimal> SalesCompYr18 { get; set; }
        public Nullable<decimal> SalesCompYr19 { get; set; }
        public Nullable<decimal> SalesCompYr20 { get; set; }
        public string FinanceYear { get; set; }
        public string FinanceMonth { get; set; }
    }
}
