//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenewalToolWriteOffAndReinCost
    {
        public System.Guid Id { get; set; }
        public System.Guid ToolId { get; set; }
        public Nullable<decimal> RENBV { get; set; }
        public Nullable<decimal> REWriteOff { get; set; }
        public Nullable<decimal> LHINBV { get; set; }
        public Nullable<decimal> LHIWriteOff { get; set; }
        public Nullable<decimal> ESSDNBV { get; set; }
        public Nullable<decimal> ESSDWriteOff { get; set; }
        public Nullable<decimal> RECost { get; set; }
        public Nullable<decimal> LHICost { get; set; }
        public Nullable<decimal> ESSDCost { get; set; }
        public Nullable<decimal> REII { get; set; }
        public Nullable<decimal> LHIII { get; set; }
        public Nullable<decimal> ESSDII { get; set; }
    }
}
