//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenewalLegalApproval
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public Nullable<int> ProcInstId { get; set; }
        public bool IsUrgency { get; set; }
        public string UrgencyReason { get; set; }
        public bool AnyLegalConcern { get; set; }
        public bool IllegalStructure { get; set; }
        public bool Occupying { get; set; }
        public bool NoAuthorityToRelease { get; set; }
        public bool EntrustLease { get; set; }
        public bool SubLease { get; set; }
        public bool BeingSealedUp { get; set; }
        public bool LicenseCantBeObtained { get; set; }
        public bool PendingOrDispute { get; set; }
        public bool OtherIssure { get; set; }
        public string BeingSealedUpDesc { get; set; }
        public string PendingOrDisputeDesc { get; set; }
        public string OtherIssureDesc { get; set; }
        public string ReviewStatus { get; set; }
        public bool SubmitBeforeSign { get; set; }
        public string SubmitBeforeSignDesc { get; set; }
        public bool LandlordFormLeaseUserd { get; set; }
        public bool OwnerRefuseToHonorLease { get; set; }
        public bool MortgageeRefuseToGuarantee { get; set; }
        public bool OtherLegalComment { get; set; }
        public string OtherLegalCommentDesc { get; set; }
        public Nullable<int> NotEndorsedIssureNo { get; set; }
        public string LegalComments { get; set; }
        public bool OptionsForRenewal { get; set; }
        public bool ReinstatementRequirement { get; set; }
        public string SOXAuditComment { get; set; }
        public string GCEndorsestate { get; set; }
        public string GCComment { get; set; }
        public string CreateUserAccount { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string LastUpdateUserAccount { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public bool IsHistory { get; set; }
        public bool IsRecentTransfer { get; set; }
        public bool IsIntermediaries { get; set; }
        public bool IsRelatedParties { get; set; }
        public bool IsBroker { get; set; }
        public bool IsPTTP { get; set; }
        public bool IsASIIWGO { get; set; }
        public bool IsNoBLClause { get; set; }
        public bool IsOFAC { get; set; }
        public bool IsAntiC { get; set; }
        public bool IsBenefitConflict { get; set; }
        public bool NoneOfAbove { get; set; }
    }
}
