//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成�?
//
//     手动更改此文件可能导致应用程序出现意外的行为�?
//     如果重新生成代码，将覆盖对此文件的手动更改�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReopenMemo
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public string ExteriorAfterImg1 { get; set; }
        public string ExteriorAfterImg2 { get; set; }
        public string InteriorAfterImg1 { get; set; }
        public string InteriorAfterImg2 { get; set; }
        public bool NewMcCafe { get; set; }
        public bool NewKiosk { get; set; }
        public bool NewMDS { get; set; }
        public bool Is24H { get; set; }
        public string TotalNetSales { get; set; }
        public string ProjIncerenentalSales { get; set; }
        public string AftOperationSize { get; set; }
        public string AftARSN { get; set; }
        public string AftARPT { get; set; }
        public Nullable<System.DateTime> ReopenDate { get; set; }
        public string DesignConcept { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> GBDate { get; set; }
        public string TTMNetSales { get; set; }
        public Nullable<decimal> IncrementalSales { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string LastUpdateUserAccount { get; set; }
        public string LastUpdateUserNameZHCN { get; set; }
        public string LastUpdateUserNameENUS { get; set; }
    }
}
