//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPFieldSetting
    {
        public int ID { get; set; }
        public Nullable<int> TableID { get; set; }
        public string FieldName { get; set; }
        public FieldConditionType ConditionType { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<int> GlobalBy { get; set; }
        public bool IsLocked { get; set; }
        public string OtherZHCN { get; set; }
        public string OtherENUS { get; set; }
        public string DispZHCN { get; set; }
        public string DispENUS { get; set; }
    }
}
