//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPSelectionSetting
    {
        public int ID { get; set; }
        public Nullable<int> FieldID { get; set; }
        public string Code { get; set; }
        public string Value { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
        public string DispZHCN { get; set; }
        public string DispENUS { get; set; }
    }
}
