//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTemplateFieldDetail
    {
        public int ID { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<int> FieldID { get; set; }
        public string ConditionText { get; set; }
        public bool IsOrderBy { get; set; }
        public bool IsDESC { get; set; }
    }
}
