//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleLog
    {
        public System.Guid Id { get; set; }
        public string USCode { get; set; }
        public string ProjectId { get; set; }
        public string CreatorUserAccount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> IsExecuted { get; set; }
        public Nullable<System.DateTime> ExecuteDate { get; set; }
        public string FlowCode { get; set; }
        public string Action { get; set; }
        public string Info { get; set; }
    }
}
