//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartProcessLog
    {
        public System.Guid Id { get; set; }
        public int ProcInstID { get; set; }
        public string UserAccount { get; set; }
        public string UserNameZHCN { get; set; }
        public string UserNameENUS { get; set; }
        public Nullable<System.Guid> RefTableId { get; set; }
        public string RefTableName { get; set; }
        public string TitleCode { get; set; }
        public string TitleNameZHCN { get; set; }
        public string TitleNameENUS { get; set; }
        public string SourceCode { get; set; }
        public string SourceNameZHCN { get; set; }
        public string SourceNameENUS { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
