//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreSTLocation
    {
        public System.Guid Id { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string StoreCode { get; set; }
        public Nullable<bool> HasPartyRoom { get; set; }
        public Nullable<bool> HasPlayPlace { get; set; }
        public Nullable<int> PoleSign { get; set; }
        public string PoleSignageCount { get; set; }
        public string DirectionalEffect { get; set; }
        public string Signage { get; set; }
        public string SignageCount { get; set; }
        public string FacadeLenth { get; set; }
        public string EgressCount { get; set; }
        public string IngressCount { get; set; }
        public string OpenCount { get; set; }
        public string McdCarParkCount { get; set; }
        public string PublicCarParkCount { get; set; }
        public string RoadCarParkCount { get; set; }
        public string CarParkTotal { get; set; }
        public string PortfolioTypeName { get; set; }
        public string DTTypeName { get; set; }
        public string Floor { get; set; }
        public string Floor1 { get; set; }
        public string Size1 { get; set; }
        public string Seats1 { get; set; }
        public string Floor2 { get; set; }
        public string Size2 { get; set; }
        public string Seats2 { get; set; }
        public string Floor3 { get; set; }
        public string Size3 { get; set; }
        public string Seats3 { get; set; }
        public string Floor4 { get; set; }
        public string Size4 { get; set; }
        public string Seats4 { get; set; }
        public string Floor5 { get; set; }
        public string Size5 { get; set; }
        public string Seats5 { get; set; }
        public string SeatingRatio { get; set; }
        public string TotalArea { get; set; }
        public string TotalSeatsNo { get; set; }
        public Nullable<int> SplitKitchen { get; set; }
        public string KitchenFloor { get; set; }
        public string FrontCounterFloor1 { get; set; }
        public string FrontCounterFloor2 { get; set; }
        public string FrontCounterSeats { get; set; }
        public string OutsideSeats { get; set; }
        public string DTSize { get; set; }
        public string DiningArea { get; set; }
        public string KitchenArea { get; set; }
        public string RemoteKioskArea { get; set; }
        public string WaitingArea { get; set; }
        public string ServiceArea { get; set; }
        public Nullable<int> PlayPlace { get; set; }
        public string SeatArea { get; set; }
        public string ProducingArea { get; set; }
        public Nullable<int> PartyRoom { get; set; }
        public string PlayPlaceArea { get; set; }
        public string BackArea { get; set; }
        public string ToiletArea { get; set; }
        public string ColdStorageArea { get; set; }
        public string StairArea { get; set; }
        public string DryArea { get; set; }
        public string OtherArea { get; set; }
        public string StaffroomArea { get; set; }
        public string DesignStyle { get; set; }
        public string ExteriorDesign { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> SyncTime { get; set; }
        public string SyncType { get; set; }
    }
}
