//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreProfitabilityAndLeaseInfo
    {
        public System.Guid RefId { get; set; }
        public Nullable<System.DateTime> LastRemodelDate { get; set; }
        public Nullable<int> RemainingLeaseYears { get; set; }
        public Nullable<decimal> TTMSales { get; set; }
        public string AsOf { get; set; }
        public Nullable<decimal> TTMSOIPercent { get; set; }
        public int Id { get; set; }
    }
}
