//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskWork
    {
        public System.Guid Id { get; set; }
        public int Num { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string SourceCode { get; set; }
        public string RefID { get; set; }
        public Nullable<TaskWorkStatus> Status { get; set; }
        public string ReceiverAccount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserAccount { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string TypeCode { get; set; }
        public Nullable<int> ProcInstID { get; set; }
        public string DoActionUser { get; set; }
        public string ActionName { get; set; }
        public string K2SN { get; set; }
        public string StoreCode { get; set; }
        public string ReceiverNameZHCN { get; set; }
        public string ReceiverNameENUS { get; set; }
        public string SourceNameENUS { get; set; }
        public string SourceNameZHCN { get; set; }
        public string TypeNameZHCN { get; set; }
        public string TypeNameENUS { get; set; }
        public string StatusNameZHCN { get; set; }
        public string StatusNameENUS { get; set; }
        public Nullable<System.Guid> RefTableId { get; set; }
        public string RefTableName { get; set; }
        public string ActivityName { get; set; }
    }
}
