//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成�?
//
//     手动更改此文件可能导致应用程序出现意外的行为�?
//     如果重新生成代码，将覆盖对此文件的手动更改�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    
    public enum TaskWorkStatus : int
    {
        UnFinish = 0,
        Finished = 2,
        Cancel = 9,
        None = -1,
        K2ProcessApproved = 200,
        K2TaskExpired = 4,
        K2ProcessDeclined = 100,
        K2Executing = 50,
        Holding = 10,
        Pending = 20
    }
}
