//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempClosureInfo
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public string USCode { get; set; }
        public System.DateTime EstimatedTempClosureDate { get; set; }
        public System.DateTime ActualTempClosureDate { get; set; }
        public System.DateTime EstimatedReopenDate { get; set; }
        public System.DateTime ActualReopenDate { get; set; }
        public string ClosureReasonCode { get; set; }
        public string ClosureReasonRemark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Modifier { get; set; }
        public string Type { get; set; }
        public string TypeNameZHCN { get; set; }
        public string TypeNameENUS { get; set; }
        public Nullable<System.DateTime> LeaseExpireDate { get; set; }
        public string LandlordName { get; set; }
        public string StoreNameZHCN { get; set; }
        public string StoreNameENUS { get; set; }
        public string AssetRepAccount { get; set; }
        public string AssetRepNameZHCN { get; set; }
        public string AssetRepNameENUS { get; set; }
        public string AssetActorAccount { get; set; }
        public string AssetActorNameZHCN { get; set; }
        public string AssetActorNameENUS { get; set; }
        public string FinanceAccount { get; set; }
        public string FinanceNameZHCN { get; set; }
        public string FinanceNameENUS { get; set; }
        public string PMAccount { get; set; }
        public string PMNameZHCN { get; set; }
        public string PMNameENUS { get; set; }
        public string LegalAccount { get; set; }
        public string LegalNameZHCN { get; set; }
        public string LegalNameENUS { get; set; }
        public string AssetManagerAccount { get; set; }
        public string AssetManagerNameZHCN { get; set; }
        public string AssetManagerNameENUS { get; set; }
        public string CMAccount { get; set; }
        public string CMNameZHCN { get; set; }
        public string CMNameENUS { get; set; }
        public string CreateUserAccount { get; set; }
    }
}
