//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempClosureReopenMemo
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public string USCode { get; set; }
        public string RegionCode { get; set; }
        public string RegionENUS { get; set; }
        public string RegionZHCN { get; set; }
        public string MarketCode { get; set; }
        public string MarketENUS { get; set; }
        public string MarketZHCN { get; set; }
        public string ProvinceENUS { get; set; }
        public string ProvinceZHCN { get; set; }
        public string CityCode { get; set; }
        public string CityENUS { get; set; }
        public string CityZHCN { get; set; }
        public string StoreENUS { get; set; }
        public string StoreZHCN { get; set; }
        public string PipelineId { get; set; }
        public Nullable<System.DateTime> ActualConsFinishDate { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public string PortfolioType { get; set; }
        public string ProtfolioTypeName { get; set; }
        public string TAClassification { get; set; }
        public string TAClassificationName { get; set; }
        public string MarketDesirability { get; set; }
        public string RERating { get; set; }
        public string BusinessArea { get; set; }
        public string KitchenFloor { get; set; }
        public string SeatingFloor { get; set; }
        public string SeatingNum { get; set; }
        public string EarlyTerminationClause { get; set; }
        public string ParkingNum { get; set; }
        public string ContractType { get; set; }
        public string Kiosk { get; set; }
        public string RERep { get; set; }
        public string RERepName { get; set; }
        public string Planner { get; set; }
        public string PlannerName { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
