//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AM_DL_Closure
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public string USCode { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string ClosureTypeCode { get; set; }
        public string ClosureTypeNameZHCN { get; set; }
        public string ClosureTypeNameENUS { get; set; }
        public string ClosureReasonCode { get; set; }
        public string ClosureReasonNameZHCN { get; set; }
        public string ClosureReasonNameENUS { get; set; }
        public string ClosureReasonRemark { get; set; }
        public string RelocationCode { get; set; }
        public string RelocationNameENUS { get; set; }
        public string RelocationNameZHCN { get; set; }
        public Nullable<int> RelocatedPipelineID { get; set; }
        public Nullable<decimal> Closure_WO_Total_Act { get; set; }
        public Nullable<decimal> Closure_Compensation_Act { get; set; }
        public Nullable<decimal> Closure_ClosingCost_Act { get; set; }
        public Nullable<bool> IsPushed { get; set; }
    }
}
