//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AM_DL_MajorLeaseChange
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public string USCode { get; set; }
        public Nullable<bool> ChangeLandlordType { get; set; }
        public string ChangeLandLordDESC { get; set; }
        public Nullable<bool> ChangeRentalType { get; set; }
        public string ChangeRentalTypeDESC { get; set; }
        public Nullable<bool> ChangeRedLineType { get; set; }
        public string ChangeRedLineTypeDESC { get; set; }
        public Nullable<bool> ChangeLeaseTermType { get; set; }
        public string ChangeLeaseTermDESC { get; set; }
        public Nullable<decimal> MLCNetWriteOff_Act { get; set; }
        public string MLC_TotalReinvestment_Act { get; set; }
        public string EditMode { get; set; }
        public string PartyAFullName { get; set; }
        public string ContractEntityName { get; set; }
        public string McdOwnership { get; set; }
        public string ContactPerson { get; set; }
        public string ContactMode { get; set; }
        public string RentType { get; set; }
        public string RentSize { get; set; }
        public string ContractTerm { get; set; }
        public string ContractType { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContraceEndDate { get; set; }
        public string ContractStartYear { get; set; }
        public string ContraceEndYear { get; set; }
        public Nullable<System.DateTime> RentPaymentStartDate { get; set; }
        public string DeadlineToNoticeLL { get; set; }
        public Nullable<int> ChangedAfter2010 { get; set; }
        public string RentStructure { get; set; }
        public Nullable<int> EarlyTerminationClause { get; set; }
        public string EarlyTerminationClauseDescription { get; set; }
        public string RentPaidTo { get; set; }
        public string RentPaymentArrangement { get; set; }
        public Nullable<int> Deposit { get; set; }
        public string DepositAmount { get; set; }
        public string WhenRefund { get; set; }
        public Nullable<int> withPenaltyClause { get; set; }
        public Nullable<int> BankGuarantee { get; set; }
        public string BankGuaranteeNumber { get; set; }
        public string BankGuaranteeAmount { get; set; }
        public Nullable<System.DateTime> BGCommencementDate { get; set; }
        public Nullable<System.DateTime> BGEndDate { get; set; }
    }
}
