//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AM_DL_Reimage
    {
        public System.Guid Id { get; set; }
        public string ProjectId { get; set; }
        public string USCode { get; set; }
        public string OriginalSeatNO { get; set; }
        public string RightSizingSeatNO { get; set; }
        public string AfterReimageSeatNO { get; set; }
        public string OriginalDesignType { get; set; }
        public string AfterReimageDesignType { get; set; }
        public string OriginalOperationArea { get; set; }
        public string AfterReimageOperationArea { get; set; }
        public string Reimage_Total_WO_Proj { get; set; }
        public string Reimage_Total_WO_Act { get; set; }
        public string Reimage_Total_Reinvestment_Proj { get; set; }
        public string Reimage_Total_Reinvestment_Act { get; set; }
        public Nullable<System.DateTime> GBDate { get; set; }
        public Nullable<System.DateTime> ReopenDate { get; set; }
        public Nullable<int> ClosureDays { get; set; }
        public Nullable<bool> IsPushed { get; set; }
    }
}
