//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VProjectComment
    {
        public System.Guid Id { get; set; }
        public int Num { get; set; }
        public string UserAccount { get; set; }
        public string UserNameZHCN { get; set; }
        public string UserNameENUS { get; set; }
        public Nullable<System.Guid> RefTableId { get; set; }
        public string RefTableName { get; set; }
        public string TypeCode { get; set; }
        public string TitleCode { get; set; }
        public string TitleNameZHCN { get; set; }
        public string TitleNameENUS { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateUserNameENUS { get; set; }
        public string CreateUserNameZHCN { get; set; }
        public string Content { get; set; }
        public Nullable<int> Status { get; set; }
        public string SourceCode { get; set; }
        public string SourceNameZHCN { get; set; }
        public string SourceNameENUS { get; set; }
        public Nullable<int> ProcInstID { get; set; }
        public string ActivityName { get; set; }
        public string PositionENUS { get; set; }
        public string PositionZHCN { get; set; }
        public string ActionDesc { get; set; }
    }
}
