//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VProject
    {
        public string ProjectId { get; set; }
        public string USCode { get; set; }
        public string AssetActorAccount { get; set; }
        public string AssetActorNameENUS { get; set; }
        public string AssetRepAccount { get; set; }
        public string AssetManagerAccount { get; set; }
        public string FinanceAccount { get; set; }
        public string PMAccount { get; set; }
        public string LegalAccount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public ProjectStatus Status { get; set; }
        public string StoreNameENUS { get; set; }
        public string StoreNameZHCN { get; set; }
        public System.DateTime OpenDate { get; set; }
        public Nullable<System.DateTime> ReImageDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string CityCode { get; set; }
        public string CityENUS { get; set; }
        public string CityZHCN { get; set; }
        public string ProvinceENUS { get; set; }
        public string ProvinceZHCN { get; set; }
        public string FlowCode { get; set; }
        public Nullable<bool> IsPushed { get; set; }
        public Nullable<System.DateTime> ReopenDate { get; set; }
        public Nullable<System.DateTime> GBDate { get; set; }
        public Nullable<System.DateTime> ConstructionFinishDate { get; set; }
        public Nullable<bool> HasHoldingProjectRight { get; set; }
        public Nullable<HoldingStatus> HoldingProjectStatus { get; set; }
    }
}
