//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VStoreList
    {
        public System.Guid Id { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string StoreCode { get; set; }
        public string NameZHCN { get; set; }
        public string NameENUS { get; set; }
        public Nullable<int> PipelineID { get; set; }
        public string PipelineCode { get; set; }
        public string PipelineNameZHCN { get; set; }
        public string PipelineNameENUS { get; set; }
        public string RegionCode { get; set; }
        public string RegionZHCN { get; set; }
        public string RegionENUS { get; set; }
        public string MarketCode { get; set; }
        public string MarketZHCN { get; set; }
        public string MarketENUS { get; set; }
        public string ProvinceZHCN { get; set; }
        public string ProvinceENUS { get; set; }
        public string CityCode { get; set; }
        public string CityZHCN { get; set; }
        public string CityENUS { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictZHCN { get; set; }
        public string DistrictENUS { get; set; }
        public string MMCode { get; set; }
        public string MMZHCN { get; set; }
        public string MMENUS { get; set; }
        public string AssetSpecialist { get; set; }
        public string TACode { get; set; }
        public string TAName { get; set; }
        public string StoreType { get; set; }
        public string StoreTypeName { get; set; }
        public string PortfolioType { get; set; }
        public string PortfolioTypeName { get; set; }
        public string DTModel { get; set; }
        public Nullable<int> IsAlliance { get; set; }
        public string AllianceCode { get; set; }
        public string AllianceCodeName { get; set; }
        public Nullable<int> TVMarket { get; set; }
        public Nullable<int> IsBigLL { get; set; }
        public string BigLLName { get; set; }
        public string statusName { get; set; }
        public string StoreStatus { get; set; }
        public string AddressZHCN { get; set; }
        public string AddressENUS { get; set; }
        public System.DateTime OpenDate { get; set; }
        public Nullable<System.DateTime> ReImageDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string DesignType { get; set; }
        public string AssetRepName { get; set; }
        public string AssetMgrName { get; set; }
    }
}
