//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcdonalds.AM.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriteOffAmount
    {
        public System.Guid Id { get; set; }
        public System.Guid ConsInfoID { get; set; }
        public string REII { get; set; }
        public string RENBV { get; set; }
        public string REWriteOff { get; set; }
        public string LHIII { get; set; }
        public string LHINBV { get; set; }
        public string LHIWriteOff { get; set; }
        public string ESSDII { get; set; }
        public string ESSDNBV { get; set; }
        public string ESSDWriteOff { get; set; }
        public string EquipmentII { get; set; }
        public string EquipmentNBV { get; set; }
        public string EquipmentWriteOff { get; set; }
        public string SignageII { get; set; }
        public string SignageNBV { get; set; }
        public string SignageWriteOff { get; set; }
        public string SeatingII { get; set; }
        public string SeatingNBV { get; set; }
        public string SeatingWriteOff { get; set; }
        public string DecorationII { get; set; }
        public string DecorationNBV { get; set; }
        public string DecorationWriteOff { get; set; }
        public string ClosingCostBudegt { get; set; }
        public string ClosingCostActual { get; set; }
        public string TotalII { get; set; }
        public string TotalNBV { get; set; }
        public string TotalWriteOff { get; set; }
        public string REActual { get; set; }
        public string LHIActual { get; set; }
        public string ESSDActual { get; set; }
        public string EquipmentActual { get; set; }
        public string SignageActual { get; set; }
        public string SeatingActual { get; set; }
        public string DecorationActual { get; set; }
        public string TotalActual { get; set; }
        public string ExpFAActVsReCost { get; set; }
        public string ExpFAActVsLHI { get; set; }
        public string ExpFAActVsESSD { get; set; }
        public string ExpFAActVsTotal { get; set; }
    }
}
